(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.h2 = function() {
	this.initialize(img.h2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,830,494);


(lib.h3 = function() {
	this.initialize(img.h3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,951,500);


(lib.light = function() {
	this.initialize(img.light);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.Logo = function() {
	this.initialize(img.Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,154,117);


(lib.tagline = function() {
	this.initialize(img.tagline);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,750,185);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3E8DCA").s().p("APxCXQgDgFgCgIQACgHADgFQAEgGAFAAQAGAAAEAGQAEAFABAHQgBAIgEAFQgEAFgGAAQgFAAgEgFgApzCXQgEgFAAgIQAAgHAEgFQAEgGAFAAQAGAAAEAGQADAFABAHQgBAIgDAFQgEAFgGAAQgFAAgEgFgAuvCXQgLgFgGgKQgFgIAAgMQgBgOAFgHQAGgIAMgFQgGgEgDgFQgEgCAAgHQAAgIAHgGQAGgHANgDQgNgGgGgLQgIgLAAgPQAAgWALgLQAMgMASAAIANABIAMAFIAgAAIAAANIgYAAQAEAFABAHQACAFAAAJQAAAKgEAJQgFAJgHAHIgGAEIgHAEIgLADQgMAEgEACQgGACgBADQgDACAAADQAAADACACQABADAGABIANABIARACIAMACIAIAEQAJAFAEAHQAFAJAAALQAAAOgHALQgGALgLAFQgMAGgPAAQgQAAgLgFgAuyBiQgKAGAAANQAAAJAGAGQAEAHAJAEQAIAEANgBQAQABALgIQAJgIAAgOQAAgNgJgGQgMgHgSAAQgSAAgJAHgAukgfQgHAKAAASQAAAQAGALQAFAJAMAAQAKAAAFgJQAHgLAAgQQAAgTgHgJQgEgLgLAAQgLAAgFALgAXyBkIgMgCQgEgCgEgEQgFgDgHgHQgHAJgJAFQgKAEgMAAQgTAAgOgNQgPgOgHgWQgJgYAAggQAAgfAJgXQAHgYAPgNQAOgMATgBQAUABAOAMQAOANAHAYQAIAXAAAhQAAAQgDAQQgDASgFAOQAHARAGAIQAGAFAIAAIAAAJgAWNhKQgKAXAAAuQAAAtAKAaQALAZAUAAQAVAAAKgYQAMgaAAgsQAAgvgMgYQgKgbgVAAQgUAAgLAbgAMsBaQgJgKgGgQQgEgRAAgVQAAgWAEgQQAGgRAJgJQALgJAMAAQAKgBAGAFQAGAGAGANIAAgnIgbAAIAAgLIAbAAIAAgEQABgKgEgEQgDgDgKAAIAAgGIATgCIARgFIAAAiIAQAAIAAALIgQAAIAACDIABANQABAEAEACIAKAAIAAAFIgMACIgJACIgJACIgDgLIAAgNQgGANgGAHQgIAGgKAAQgMAAgMgKgAMsAaQAAAgAHAQQAHARANAAQAMAAAGgQQAHgRAAgeQAAghgHgQQgGgSgNAAQgaAAAABBgAhVBaQgLgKgGgQQgGgQAAgWQAAgYAGgPQAGgRALgJQAKgKAPAAQAIgBAEADQAGADAGAIIAGgQIAEAAIAAAzIgFAAIgCgOIgEgJQgDgIgGgEQgGgFgGgBQgOAAgHASQgIATAAAfQAAAgAHAPQAHAQANAAQAXAAAFgnIAIAAQgCAXgKAOQgJAMgQABQgOgBgKgJgAklBaQgKgKgHgQQgFgQAAgWQAAgYAFgPQAHgRAKgJQALgKAOAAQAIgBAFADQAFADAGAIIAGgQIAEAAIAAAzIgEAAIgDgOIgEgJQgDgIgGgEQgFgFgIgBQgNAAgGASQgIATAAAfQAAAgAHAPQAGAQAOAAQAWAAAFgnIAJAAQgDAXgJAOQgKAMgQABQgOgBgKgJgAPaBQQgNgWAAghQAAgXAGgRQAGgPALgJQAKgJANgBQAVABALATQALAQABAjIhHAAQAAAQACAIQABAKACAIQAEAMAGAHQAHAGAKAAQANAAAGgJQAJgLACgTIAJAAQgCAXgMAOQgKAMgSAAQgWAAgNgTgAQTALQAAgagGgOQgFgNgNAAQgLAAgGAOQgHANgBAaIAxAAIAAAAgAKDBQQgMgWAAghQAAgXAGgRQAGgPAKgJQAKgJAOgBQAUABALATQALAQACAjIhHAAIAAAYIAFASQACAMAHAHQAHAGAKAAQAMAAAIgJQAIgLACgTIAKAAQgDAXgLAOQgMAMgSAAQgVAAgNgTgAK9ALQgBgagGgOQgGgNgLAAQgMAAgGAOQgHANgCAaIAzAAIAAAAgAGjBXIAAgQQgGAPgHAGQgJAHgKgBQgKAAgHgEQgIgEgEgIQgDgGgCgHIgBgUIAAhEQAAgLgCgEQgEgFgLABIAAgGIASgBIARgGIAABkQAAATAGAJQAFAIALABQANAAAFgLQAGgKAAgVIAAg/QABgLgEgEQgDgFgKABIAAgGIASgBIASgGIAAB6IABAKQABAEAEABIAKABIAAAEQgJABgIADQgIABgHADIgBgMgADzBXQgIgJAAgSQAAgPAEgKQAIgKAOgHQAHgFAJgCIASgDIAAgSIgBgOQAAgFgCgCQgCgFgEgCQgFgDgFAAQgJAAgEAFQgHAGAAAGIAAADIABAFIAAABQAAAGgDADQgDAFgEAAQgEAAgCgEQgCgDAAgEQAAgLAFgHQAGgJAJgFQAIgEALAAQAKAAAIAEQAIAEAFAJQACAFACAIQABAHAAALIAAA+QAAAQADAGQACAFAEAAIADAAIADAAIAAAHIgGACIgGAAQgJAAgFgGQgEgFgBgOQgFAOgIAGQgHAGgMAAQgPAAgIgMgAEHAdQgLAMAAARQABAOAEAGQAGAJAJAAQAMAAAGgMQAFgLAAgWIAAgcQgXAGgJAJgAjNBXQgJgJAAgSQAAgPAGgKQAGgKAOgHQAIgFAJgCIASgDIAAgSIgBgOQAAgFgDgCQgCgFgEgCQgFgDgEAAQgJAAgGAFQgGAGAAAGIAAADIABAFIAAABQAAAGgDADQgBAFgFAAQgEAAgCgEQgCgDAAgEQAAgLAFgHQAGgJAIgFQAJgEAKAAQAKAAAJAEQAIAEAFAJQACAFABAIQACAHAAALIAAA+QAAAQACAGQABAFAGAAIADAAIAEAAIAAAHQgFACgDAAIgGAAQgIAAgFgGQgEgFgBgOQgGAOgHAGQgIAGgLAAQgOAAgJgMgAi6AdQgKAMAAARQAAAOAEAGQAGAJAKAAQALAAAGgMQAGgLAAgWIAAgcQgWAGgLAJgAqKBQQgNgWAAghQAAgXAGgRQAGgPALgJQAKgJAOgBQAUABALATQALAQABAjIhGAAIABAYIAEASQACAMAHAHQAIAGAJAAQAMAAAIgJQAIgLADgTIAIAAQgDAXgKAOQgLAMgSAAQgWAAgNgTgApQALQAAgagHgOQgGgNgLAAQgMAAgGAOQgGANgCAaIAyAAIAAAAgA0bBXQgJgJAAgSQAAgPAGgKQAHgKAOgHQAIgFAJgCIARgDIAAgSIAAgOQgBgFgCgCQgCgFgDgCQgFgDgFAAQgKAAgEAGQgGAFAAAHIAAADIAAADIABACQAAAGgEADQgCAFgFAAQgEAAgBgEQgDgDAAgEQAAgLAGgHQAFgJAJgFQAIgEALAAQALAAAHAEQAJAEAEAJQADAFACAIQACAHAAALIAAA+QAAAQABAGQACAFAEAAIADAAIADAAIAAAHIgGACIgGAAQgJAAgEgGQgFgFgBgOQgFAOgHAGQgIAGgMAAQgOAAgJgMgA0HAdQgKAMAAARQABAOAFAGQAEAJAKAAQAMAAAGgMQAEgKAAgYIAAgbQgVAGgLAJgASdBgIgNAAIgLAAIgOACIAAgHQAJAAADgEQADgDAAgJIAAhLIgBgPQAAgEgDgFQgBgGgFgCQgEgDgHAAQgHAAgEAEQgFACgDAGQgDAFgBAGQgCAGAAAIIAABJQAAAJADADQAFAEAIAAIAAAHIgOgCIgLAAIgLAAIgQACIAAgHQAMgBADgDQADgDAAgKIAAhcQAAgJgBgDQgBgFgEgBIgMAAIAAgHIATgCQAHgDAGgEIABALIABAQQAHgMAIgHQAHgEALAAQAJAAAHAEQAHAFAGAKQADAFACAIIABARIAABJQgBAKAEADQADADAKABIAAAHIgNgCgAOyBgIgMAAIgLAAIgPACIAAgHQALgBADgDQAEgDAAgKIAAheQAAgLgDgDQgEgFgLABIAAgGIATgBIARgGIAAB9QAAAKADADQADADALABIAAAHIgPgCgAJmBgIgLAAIgLAAIgPACIAAgHIAJgCQABgBABAAQAAgBAAAAQABgBAAAAQAAgBAAAAIAAgDIgDgFIgTgrIgWAnIgDAIIgBAEQAAAAAAABQABAAAAABQABAAAAABQABAAABABQACACAHAAIAAAHQgGgBgDgBIgGAAIgEAAIgFAAIgFAAQgEABgGABIAAgHQAGAAADgCQAEgCACgDQAEgEADgHIAagvIgYg2QgDgHgEgCQgFgEgHAAIAAgGIAOACIALAAIAKAAIAOgCIAAAGQgGAAgDACQgBACAAADIAAACIABAFIAPAgIASgfIADgFIAAgDQAAgDgCgCQgEgCgFAAIAAgGIAKACIAJAAIAHAAIAMgCIAAAGQgGAAgDACQgEAAgCAEIgFAHIgXAqIAcA9QACAHADAEQACACAEABQAEACAFAAIAAAHIgOgCgADPBgIgLAAIgMAAIgOACIAAgHQAJAAAEgEQAEgDgCgJIAAhMQAAgSgEgIQgEgIgKABQgMAAgGAIQgGAKAAAQIAABLQAAAJADADQADAEAJAAIAAAHIgMgCIgMAAIgLAAIgOACIAAgHQAJAAADgEQAEgDAAgJIAAhLIgBgPQgBgGgCgDQgCgGgEgCQgDgCgHAAQgGAAgFADQgFADgDAHQgDAFAAAFIgBANIAABJQAAAJADADQADAEAJAAIAAAHIgOgCIgMAAIgKAAIgQACIAAgHQAMgBACgDQAEgDgBgKIAAhcIAAgLIgBgFQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIgMAAIAAgHIASgCQAHgDAGgEIACANIAAANQAHgMAIgGQAHgEALAAQAKAAAHAEQAHAHAEAMQAGgNAIgGQAHgEAMAAQAJAAAIAEQAHAEAEAKQACAEABAIQACAHAAALIAABKQgBAKADADQADADAKABIAAAHIgOgCgAmOBgIgLAAIgMAAIgNACIAAgHQAIAAADgEQAFgDgBgJIAAhMQAAgSgFgIQgFgIgJABQgMAAgGAIQgGAKAAAQIAABLQAAAJADADQADAEAJAAIAAAHIgNgCIgLAAIgMAAIgNACIAAgHQAJAAADgEQADgDAAgJIAAhLIAAgPIgDgJQgDgGgDgCQgDgCgHAAQgFAAgGADQgFADgDAHQgDAFAAAFIgBANIAABJQAAAJADADQADAEAJAAIAAAHIgOgCIgMAAIgLAAIgPACIAAgHQAMgBACgDQAEgDgBgKIAAhcIAAgLQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBgBAAAAIgMAAIAAgHIASgCQAHgDAGgEIACANIABANQAGgMAHgGQAIgEALAAQAKAAAHAEQAHAHAEAMQAGgNAIgGQAHgEAMAAQAJAAAIAEQAHAEAEAKIADAMIABASIAABKQAAAKACADQAEADALABIAAAHIgPgCgAqyBgIgLAAIgLAAIgPACIAAgHQAKgBADgDQAEgDAAgKIAAheQAAgLgEgDQgDgFgKABIAAgGIASgBIARgGIAAB9QAAAKADADQAEADAKABIAAAHIgPgCgArvBgIgMAAIgLAAIgPACIAAgHQAKAAADgEQAEgDAAgJIAAhLQAAgIgCgHIgCgJQgDgGgFgCQgDgDgHAAQgFAAgGAEQgFACgEAGQgCAFgBAGIgBAOIAABJQgBAJAFADQABAEAKAAIAAAHIgOgCIgLAAIgNAAIgOACIAAgHQALgBADgDQAEgDgBgKIAAiXQABgLgEgEQgCgDgMAAIAAgGIATgCIASgFIAABPQAEgKAJgFQAGgEAKAAQAKAAAHAEQAHAFAFAKQAEAFAAAIQACAIAAAJIAABJQAAAKADADQAEADAKABIAAAHIgOgCgAveBgIgLAAIgLAAIgOACIAAgHQAJAAADgEQAEgDAAgJIAAhLQAAgIgBgHQgBgEgCgFQgDgGgEgCQgEgDgHAAQgGAAgFAEQgFACgCAGQgEAFAAAGQgCAGAAAIIAABJQAAAJADADQADAEAJAAIAAAHIgNgCIgLAAIgNAAIgOACIAAgHQALgBACgDQAEgDAAgKIAAhcQAAgJgBgDQgBgFgDgBIgMAAIAAgHIASgCQAIgDAGgEIABALIAAAQQAIgMAHgHQAIgEAKAAQAJAAAIAEQAGAFAGAKQADAFACAIIABARIAABJQAAAKADADQADADAKABIAAAHIgPgCgAyVBgIgMAAIgLAAIgPACIAAgHQALgBACgDQAEgDAAgKIAAheQAAgLgDgDQgDgFgLABIAAgGQAKAAAJgBIARgGIAAB9QAAAKADADQAEADAKABIAAAHIgPgCgA1XBgIgLAAIgMAAIgPACIAAgHQAKgBAFgDQADgDgBgKIAAhcQABgKgCgEQgBgEgDgBQgEgBgIAAIAAgGQAJAAAJgBIANgGIACAKIAAAJIAAALQAEgOAIgIQAIgGAIAAQAJAAAGAGQAGAHAAALQAAAHgDADQgCAEgEAAQgFAAgEgCQgCgCAAgFIAAgDIABgEIAAgCQAAgBAAgBQAAgBAAAAQgBgBAAAAQAAgBgBAAQgBgDgDABQgKgBgFANQgGANAAAWIAAA/QgBAKAEADQAEADALABIAAAHIgQgCgA2zBgIgNgBIgNABQgHAAgJACIAAgJQAIgBADgBQAFgBACgEQABgGgBgGIAAimIgLAAQgJAAgFAEQgGAEgEAHQgDAJgCANIgHAAIAIgtIBnAAIAGAtIgGAAQgDgNgEgJQgEgHgEgEQgEgEgJAAIgPAAIAACmQgBAGACAGQAAAEAGABIAMACIAAAJQgKgCgGAAgATrBgIAAgHIANgCQAEgCACgEQABgFAAgHIAAiSQAAgIgBgDQgCgGgEgBQgEgBgJgBIAAgHIBoAAIADAtIgFAAQgDgWgHgHQgGgIgMAAIghAAIAABUIAhAAQAIAAACgFQADgGAAgOIAHAAIAAA5IgHAAQAAgNgDgHQgDgDgJAAIgfAAIAABIQgBALACADQAEAEAKAAIAQAAQAKAAAFgDQAHgDAFgKIAFgYIAHAAIgHAxgAz/hGIAAgSIAIAAIAFgCIADgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBIABgFQAAgEgDgEQgEgDgFAAIgFABIgIADIgCgKIALgEQAEgBAFgBQAKABAGAGQAGAHAAAJQAAALgEADQgGAGgIAAIgDAAIgEAAIAAALgAQVhGIgagaIgZAaIgLAAIAfgtIALAAIAgAtgAEwhGIgagaIgZAaIgLAAIAegtIAMAAIAfAtgAi3hGIAYgtIAZAAIglAtgApPhGIgZgaIgZAaIgLAAIAfgtIALAAIAfAtgAOdhMQgEgFAAgHQAAgIAEgFQADgEAGAAQAFAAAEAEQADAFAAAIQAAAHgDAFQgEADgHABQgEgBgDgDgArHhMQgEgFAAgHQAAgIAEgFQACgEAHAAQAFAAADAEQAEAFAAAIQAAAHgEAFQgDADgGABQgGgBgCgDgAyrhMQgDgFAAgHQAAgIADgFQADgEAHAAQAFAAAEAEQADAFAAAIQAAAHgDAFQgEADgGABQgGgBgDgDgAEhh4QgDgBgDgDIgJgIIgGgDIgEgCQgFgBgEAEQgEAEgBAIIgHgEIAEgNQABgFACgDIAHgGQAEgCAEAAIAGABIAGAEIAJAHQADAEADABIAEABQAFAAADgEQAEgDACgJIAGACIgCAOIgFAJIgHAHQgEACgEAAIgFgBg");
	this.shape.setTransform(93.725,11.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59.3,-4.3,306.1,31.2);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.h3();
	this.instance.setTransform(-125,-56,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125,-56,475.5,250);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.h2();
	this.instance.setTransform(-112,-42,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-112,-42,415,247);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3E8DCA").s().p("AtmCXIgOAAIgKAAIgRABIAAgGQAMAAADgDQAEgGAAgIIAAilQAAgIgCgEQgCgFgDgBIgMAAIAAgHIANgBQAHAAADgCIAKgDIACAMIABAQQAGgPAJgGQAGgGALAAQANAAAKALQALAJAFATQAHARAAAWQAAAXgHASQgEASgLAKQgKAKgOAAQgJABgIgHQgFgEgIgPIAAA/QgBAIAFAGQADADAKAAIAAAGIgOgBgAtigoQgHASAAAfQAAAkAHATQAHASAOAAQAOAAAHgRQAGgTAAghQAAgigGgSQgIgRgNgCQgOAAgHASgAKBCSQgMgGgHgKQgFgJgCgOQAAgMAHgJQAFgIAMgGQgGgDgDgEQgFgFAAgGQAAgJAIgHQAGgGANgEQgNgHgHgKQgHgLgBgSQAAgWAMgNQAMgNAUAAIANACQAGACAGADIAgAAIAAAOIgXgBIAFANQABAHAAAHQABAMgFAKQgDAKgJAHIgFAEIgJAEIgNAEIgPAFQgFADgDADIgBAFIABAGQACADAEAAIAPACIARABIAMAEIAKADQAIAFAFAJQAFAKAAAKQgBARgFALQgHAJgMAIQgNAGgOAAQgQAAgLgGgAJ7BaQgKAIgBALQACAKAFAHQAFAIAJADQALADALAAQASABAKgHQAKgJAAgPQAAgNgKgHQgMgHgUAAQgSAAgKAHgAKJgwQgFALgBATQABASAFALQAHAKALAAQAKAAAHgKQAFgLAAgTQAAgTgFgKQgGgLgKAAQgMABgHAKgAGnCSQgEgGgBgHQABgIAEgFQADgGAHABQAFgBAEAGQAEAFAAAIQAAAHgEAGQgEAGgFAAQgHAAgDgGgAWOBNQgPgNgJgZQgHgZAAghQAAgjAHgYQAJgYAPgOQAQgNAUAAQAKAAAKAFQAKADAIAKIAKgUIAEAAIAABBIgFAAIgEgQIgFgNQgFgMgKgHQgJgFgLgBQgXAAgNAaQgMAaAAAxQAAAxAMAaQAMAaAXABQAJAAAHgDQAIgEAIgGIAAg2QAAgKgDgDQgEgCgKgBIAAgHIAPABIALAAIANAAIAQgBIAAAHQgIAAgEABQgEACgBADIgBAKIAAA0QgPANgNAFQgNAFgNAAQgUAAgQgOgAOKBRQgKgJgHgSQgFgRAAgZQAAgXAFgRQAHgTALgJQAMgLAOAAQANAAAMALQAKAKAGAUIAEgKQACgFAAgHIgCAAIgCAAQgEAAgEgDQgCgDAAgHQAAgGACgFQAGgEAEAAQAHAAADAGQADAEAAALQAAAGgCAFQAAAGgDAGIgJARIgBABQACAGAAAHIABAMQAAAXgFATQgIASgJAKQgLAKgOAAQgPAAgLgKgAOPgoQgIASAAAiQAAAjAIATQAIARAMAAQAOAAAGgRQAIgTAAgiQAAgjgIgSQgGgTgNAAQgMAAgJATgAMnBSQgLgKgFgSQgGgRAAgYQAAgXAGgSQAFgTAMgJQALgLAOAAQAJgBAFAEQAGACAFAJIAHgRIAEAAIAAA2IgFAAIgDgPIgEgIQgCgKgHgEQgGgGgIAAQgNAAgIAUQgHASAAAiQAAAhAHASQAHARANAAQAYAAAEgrIAKAAQgCAbgKAMQgJAOgRAAQgOAAgMgJgAGXBRQgLgJgFgSQgGgRAAgZQAAgXAGgRQAGgTALgJQALgLAOAAQAOAAALALQALAJAFATQAGARAAAYQAAAYgHAQQgGASgLAKQgKAKgNAAQgPAAgLgKgAGbgoQgGASAAAiQAAAjAGATQAIARANAAQAOAAAHgRQAHgTAAgiQAAgjgHgSQgHgTgNAAQgNAAgJATgAEgBSQgLgKgFgSQgGgRAAgYQAAgWAGgSQAFgSALgJQAKgLANAAQAJAAAHAFQAGAGAGAOIAAgpIgcAAIAAgMIAcAAIAAgEQABgMgDgDQgEgEgJAAIAAgFIATgDQAIgCAJgDIAAAkIARAAIAAAMIgRAAIAACKQAAAKABAEQAAAFAFABQADACAJAAIAAAEIgOACIgJABIgKAFIgCgOIAAgLQgGANgIAGQgGAHgLgBQgOAAgKgJgAEeANQAAAhAGATQAIASAOAAQAMAAAIgRQAGgSAAgiQAAghgGgUQgIgQgOAAQgaAAAABEgAB6BFQgOgVAAglQAAgWAGgRQAGgTAKgJQAMgKAOgBQAVACAMARQAKAVABAjIhIAAIABAbQABAKACAIQAFAOAGAHQAIAGAJABQAOAAAHgMQAIgKADgVIAJAAQgCAZgMAOQgLAOgTAAQgWABgNgXgAC1gCQAAgdgHgNQgGgOgNgBQgKABgHAOQgJANAAAdIA0AAIAAAAgAhwBWQgGgEgDgJQgCgEAAgIQgCgHAAgKIAChfIgRAAIAAgKQAMgBAHgLQAJgNADgWIAFAAIAAAuIAdAAIAAALIgdAAIAABcQAAAVACAIQAFAIAIABIAGgCIAKgFIAAAJQgHAFgGADQgFACgGAAQgJAAgGgFgAjkBFQgMgVAAglQgBgWAGgRQAFgTAMgJQAJgKAPgBQAWACAMARQAKAVABAjIhJAAIACAbQAAAKACAIQAFAOAHAHQAGAGALABQANAAAHgMQAJgKACgVIAKAAQgDAZgMAOQgLAOgSAAQgXABgNgXgAipgCQgBgdgFgNQgHgOgMgBQgMABgGAOQgHANgCAdIA0AAIAAAAgAnbBWQgHgEgDgJQgCgEgBgIQgBgHAAgKIABhfIgPAAIAAgKQAMgBAHgLQAIgNADgWIAGAAIAAAuIAdAAIAAALIgdAAIAABcQAAAVACAIQAEAIAIABIAHgCQADgBAGgEIAAAJQgGAFgHADQgFACgGAAQgJAAgFgFgAqLBQQgIgLgCgUQAAgPAIgLQAGgJAOgJQAIgEAJgCQAJgEAKgBIAAgTIAAgOQgBgGgCgDQgCgFgFgBQgEgEgFAAQgJABgHAFQgEAEAAAJIAAAAIAAAHQgBAIgCAEQgCAEgGAAQgEAAgCgDQgBgEAAgEQAAgLAEgKQAGgIAJgFQAKgEALgBQAJABAJAEQAJAFAFAIQADAGAAAIQADAJAAAMIAABBQAAARACAFQACAHAFAAIACAAIAEgBIAAAIIgIACIgFABQgKAAgEgIQgFgFAAgOQgGANgJAHQgHAHgMAAQgPAAgJgLgAp1ASQgMALAAASQAAANAGAJQAFAIAKAAQAMAAAHgLQAEgMAAgZIAAgbQgWAEgKAMgAzdBQQgKgLAAgUQAAgPAIgLQAHgJANgJQAJgEAJgCQAIgEALgBIAAgTQAAgJgCgFQAAgGgCgDQgCgFgFgBQgEgEgFAAQgJABgFAFQgGAEAAAJIAAAAIAAAHQAAAIgCAEQgDAEgFAAQgEAAgDgDIAAgIQAAgLAEgKQAFgIAJgFQAKgEAKgBQAMABAHAEQAKAFADAIQAEAGACAIQACAJAAAMIAABBQgBARACAFQACAHAFAAIADAAIAEgBIAAAIIgIACIgGABQgJAAgFgIQgEgFgBgOQgGANgIAHQgHAHgMAAQgPAAgKgLgAzHASQgLALAAASQAAANAFAJQAGAIAJAAQANAAAGgLQAFgMAAgZIAAgbQgXAEgKAMgAVWBWIgJAAIgJAAIgNAAQgGAAgLADIAAgIQALgBAEgDQAEgEAAgHIgCisIgoCPIgEAMIgCAJIgEANIgCALIgEAAIg0i9IgHCqQAAAJAGAEQADAEAMABIAAAIIgNgBIgKgCIgLACIgPABIAAgIQAJgBAFgBQADgCACgFQACgDAAgKIAFieQAAgLgEgEQgDgDgNgBIAAgJIALACIAJAAIAKAAIANgCIAuCiIAuiiIANACIALAAIAIAAIAKgCIAAAIQgLACgDADQgGADABALIADCfQAAAKACADQAAAEAEADQAFABAIABIAAAIIgMgDgASWBWIgOAAIgOAAQgHAAgKADIAAgIQAJAAAFgEQADgBAAgEIAAgGQgCgDAAgDIgIgiIg4AAIgJAeIgDAJIAAAGQAAAFADADQADABAJABIAAAIIgMgBQgFgCgGAAQgFAAgEACIgOABIAAgIQAIAAADgCQAFgCADgFQACgDACgLIA5i+IAxDBQACAIAEAEQACAEADACQAFABAIABIAAAIQgJgDgHAAgARuAQIgYhiIgcBiIA0AAgAJUBWIgMAAIgMAAIgOADIAAgGQAJgBADgDQAEgFAAgIIAAhPQAAgJgBgGIgDgLQgDgHgEgDQgFgDgFAAQgHABgGADQgFACgDAHQgEAFgBAHIAAARIAABMQgBAIAEAFQADADAJABIAAAGIgPgDIgLAAIgMAAIgPADIAAgGQAMgBADgDQAEgFgBgJIAAhjIgBgOQgBgDgEgCIgMAAIAAgHIAUgDIAOgGIACALIAAARQAGgNAJgHQAIgEAKgBQAJABAJAEQAHAFAFAKIAEAOIACAUIAABNQAAAJACAFQAFADAJABIAAAGIgOgDgABeBYIgIAAIgHAAIgKABIgjhVIgSAYIAAAlQAAAJAEAFQADADALABIAAAGIgPgDIgMAAIgKAAIgQADIAAgGQAKgBAEgDQAEgFAAgJIAAihQAAgMgEgEQgEgEgKAAIAAgFIASgDIARgFIAACPIAog3QAEgDAAgCIAAgEQAAgEgDAAQgEgEgFAAIAAgGQAFACAHAAIAJAAIANAAQAEAAAIgCIAAAGQgGAAgEADQgEABgDADIgIAJIgXAgIAkBLIAEALIAHAFQAEACAGAAIAAAGIgJgBgAkKBWIgLAAIgMAAIgOADIAAgGQAKgBADgDQAEgFgBgJIAAhlQABgMgEgDQgDgDgKAAIAAgHIASgCIATgGIAACGQgBAJADAFQADADAMABIAAAGIgRgDgAlEBWIgLAAIgNAAIgPADIAAgGQAKgBAEgDQADgFgBgIIAAhPIAAgRIgCgJQgEgHgEgDQgFgDgGAAQgGABgHADQgEACgEAHIgEAMQgBAFAAAMIAABMQgBAIAFAFQACADAKABIAAAGIgPgDIgLAAIgMAAIgOADIAAgGQAJgBAFgDQAEgFAAgJIAAihQAAgMgEgEQgFgEgJAAIAAgFIATgDQAIgCAJgDIAABVQAHgKAGgHQAJgEAJgBQAKABAIAEQAIAFAFAKIAEAOIABAUIAABNQAAAJAEAFQADADAKABIAAAGIgOgDgAqqBWIgNAAIgMAAIgPADIAAgGQAKgBAEgDQADgFAAgIIAAhPIgBgRIgCgJQgFgHgDgDQgFgDgGAAQgHABgFADQgFACgEAHQgDAFAAAHQgCAFAAAMIAABMQgBAIADAFQAEADAKABIAAAGIgOgDIgNAAIgLAAIgPADIAAgGQAKgBAFgDQADgFAAgJIAAihQAAgMgDgEQgFgEgKAAIAAgFIAUgDQAJgCAIgDIAABVQAGgKAIgHQAIgEAJgBQAKABAHAEQAIAFAGAKQACAHABAHQACAIAAAMIAABNQgBAJAGAFQACADALABIAAAGIgOgDgAvWBWIgMAAIgMAAIgPADIAAgGQALgBADgDQADgFgBgIIAAhSQAAgTgEgJQgFgHgKAAQgNAAgFAJQgHAKAAATIAABPQABAIACAFQAEADAKABIAAAGIgPgDIgLAAIgLAAIgQADIAAgGQAKgBAEgDQACgFABgIIAAhSIgBgQQAAgEgDgEQgCgGgDgDQgFgCgGAAQgGAAgGADQgFAEgDAHIgEALIAAAQIAABMQAAAIACAFQAFADAIABIAAAGIgPgDIgLAAIgNAAIgOADIAAgGQALgBADgDQAFgFAAgJIAAhjIAAgLQgBgEgCgCIgFgCIgKAAIAAgHIASgDIAOgGQACAGAAAIIAAANQAHgMAIgHQAIgEAJgBQAMABAIAEQAGAHAGANQAFgNAIgHQAIgEAMgBQAKABAIAEQAHAFAEAIQADAHAAAHIABASIAABRQABAJACAFQAEADAKABIAAAGIgOgDgAz8BWIgLAAIgOAAIgOADIAAgGQALgBADgDQADgFgBgIIAAhPIAAgRIgCgJQgDgHgFgDQgFgDgGAAQgGABgHADQgEACgDAHIgFAMQgBAFAAAMIAABMQgBAIAFAFQACADAKABIAAAGIgPgDIgLAAIgMAAIgPADIAAgGQALgBAEgDQADgFABgJIAAihQgBgMgDgEQgEgEgLAAIAAgFIATgDQAJgCAJgDIAABVQAGgKAHgHQAIgEAKgBQALABAHAEQAIAFAFAKQADAHABAHQADAIAAAMIAABNQgCAJAEAFQADADAKABIAAAGIgOgDgA15BWIgPAAIgOAAQgGAAgLADIAAgIQAJAAAEgEQAEgBgBgEQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBgBgBIgDgIIgthUIgIAPIAABEIABANQAAAEAFADQAEABAIABIAAAIQgJgDgGAAIgNAAIgKAAIgJAAIgMADIAAgIQAIgBAFgBQAFgDABgEQABgDAAgKIAAicQAAgIgBgGQgBgEgFgBQgFgCgIgBIAAgIIASADIANAAIANAAIAQgDIAAAIQgJABgEACQgEABgBAEIgBAOIAABJIA3hRQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAIABgEQAAgEgEAAQgCgCgKgBIAAgIQAJACAFAAIAMAAIAKAAQAHAAAJgCIAAAIQgJABgFACQgEAAgFAEIgIAKIgqA9IA4BlQACAJAFADQADAFAFACQAEACAIAAIAAAIQgKgDgIAAgApzhYIAZgvIAbAAIgpAvgAzEhYIAYgvIAbAAIgoAvgAHLhZIgagbIgbAbIgMAAIAgguIAMAAIAgAugAC3hZIgbgbIgbAbIgKAAIAfguIAMAAIATAbIAVgrIAbAAIgoAwIgFAAIAKAOgAinhZIgbgbIgaAbIgLAAIAfguIAMAAIATAbIAVgrIAbAAIgnAwIgFAAIAJAOgAkfhgQgEgGAAgGQAAgIAEgGQADgEAGAAQAGAAAEAEQACAGAAAIQAAAGgDAGQgDAGgGAAQgGAAgDgGg");
	this.shape.setTransform(88.3,-60.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64.7,-76.1,306,30.39999999999999);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AlyFTQgiAAAAgkIAApdQAAgkAiAAILlAAQAiAAAAAkIAAJdQAAAkgiAAg");
	this.shape.setTransform(863.425,222.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.instance = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,970,256.4);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.tagline();
	this.instance.setTransform(174,28,0.46,0.46);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_2
	this.instance_1 = new lib.light();
	this.instance_1.setTransform(-140,-32);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-140,-32,970,250);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AC0A+QgCgCAAgDQAAgBAAAAQAAgBAAgBQABAAAAgBQABAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAQABAAABAAQADAAABACQABABAAAAQABABAAAAQAAABAAABQAAAAAAABQAAADgCACQgBACgDAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAgAhWA+QgCgCAAgDQAAgBAAAAQAAgBABgBQAAAAAAgBQABAAAAgBQACgCADAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABABAAAAQABABAAAAQAAABAAABQABAAAAABQAAADgDACQgCACgCAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAgALcAjQgEgFAAgJIAIAAQAAAHADADQAFAFAIAAQAGAAAFgDQADgDAAgGQAAgFgDgEIgLgGQgLgEgEgDQgHgEAAgJQAAgIAHgGQAGgEAJAAQALAAAGAIQADAEABAIIgIAAQAAgGgDgDQgEgEgGAAQgGAAgDADQgFADAAAFQAAAEAFADIAMAGIAKAFIAGAEQAEAFAAAHQAAAKgIAGQgGAEgJAAQgNAAgHgIgAH0AjQgJgLAAgRQgBgTALgKQAIgHALAAQAKAAAGAFQAGAGABAKIgHAAQgDgOgNAAQgKAAgFAIQgGAIAAANQAAAPAHAIQAFAGAJAAQAHAAAEgEQAFgFABgJIAIAAQgCAJgDAGQgHAKgNAAQgNAAgHgIgABmAkQgEgEgBgHIgBgMIAAgpIAIAAIAAApIABALIACAFQABAEAFACQADABAGAAQAGAAAEgCQAGgEAAgIIAAgJIAAgpIAIAAIAAApIAAAMIgCAFQgCAHgHADQgFADgIAAQgOAAgGgHgAjiAjQgKgKAAgSQAAgSAJgKIAJgGQAGgCAFAAQAKAAAHAFQAGAGABAKIgHAAQgBgGgEgEQgEgEgIAAQgJAAgFAGQgHAJABAOQgBAQAIAIQAFAFAJAAQAJAAAIgEIAAgSIgPAAIAAgHIAWAAIAAAdQgKAHgOAAQgNAAgHgIgAmEAmQgGgFgBgJQABgIAGgHIAIgHIgHgIIgBgHQAAgGAEgEQAEgEAIAAQAGAAADADQAEAEAAAGQABAFgDAFQgCAEgHAEIAPAUQACgFABgJIAGAAIAAACIgBAKQgBAEgDAEIAJAMIgJAAIgEgGIgGAFQgGACgGAAQgJAAgGgFgAl/AOQgEAEAAAGQAAAFAEAEQAEAEAHAAQAIAAAEgHIgQgWIgHAGgAl6gTQgDACAAADIABAFIAGAJIAGgHQACgDAAgEQAAgDgCgCQgCgCgDAAQgDAAgCACgAPiAqIAAgGIAkg5IgiAAIAAgHIAsAAIAAAGIglA5IAkAAIAAAHgAPMAqIgig6IAAA6IgHAAIAAhGIAJAAIAiA6IAAg6IAHAAIAABGgANuAqIAAhGIAnAAIAAAHIggAAIAAAXIAeAAIAAAHIgeAAIAAAaIAhAAIAAAHgAMzAqIAAhGIANAAQANAAAEACQAGACADAFQADAEAAAFQAAALgNADQAQAEAAAOQAAAKgGAFQgDADgGABIgSABgAM7AjIAHAAIAKAAIAFgBQAEgCABgDQACgDgBgEQAAgEgBgEQgCgDgFgBIgNgBIgHAAgAM7ACIAHAAQAJAAAEgCQAFgCABgHQAAgEgCgDQgCgDgDgBIgMgBIgHAAgAKmAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAJjAqIAAhGIAMAAIAOABQANACAHAKQAHAJAAANQAAAOgIAKQgHAJgMACIgPAAgAJsAjIAFAAIAMAAIAHgDQAGgEADgGQADgHAAgIQgBgMgGgIQgFgGgIgBIgNgBIgDAAgAIuAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAHaAqIgSgeIgNAAIAAAeIgIAAIAAhGIANAAIAMABIAIACQAGACADAFQACAFAAAFQAAANgOAGIATAfgAG7AFIAGAAIAJAAIAFgBQAIgDAAgJQAAgIgGgDIgGgCIgKAAIgGAAgAF+AqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAFkAqIAAg+IgVA+IgIAAIgUg+IAAA+IgIAAIAAhGIANAAIAUA9IATg9IAMAAIAABGgADrAqIAAg/IgTAAIAAgHIAtAAIAAAHIgSAAIAAA/gADNAqIgHgTIgbAAIgGATIgJAAIAZhGIAHAAIAZBGgACtARIAXAAIgLgjgABHAqIAAgiIgiAAIAAAiIgIAAIAAhGIAIAAIAAAeIAiAAIAAgeIAIAAIAABGgAgIAqIAAg/IgSAAIAAgHIAsAAIAAAHIgSAAIAAA/gAhjAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAh9AqIAAgiIgiAAIAAAiIgIAAIAAhGIAIAAIAAAeIAiAAIAAgeIAIAAIAABGgAkEAqIgig6IAAA6IgHAAIAAhGIAJAAIAiA6IAAg6IAHAAIAABGgAnWAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAnrAqIgRgdIgSAdIgJAAIAWglIgUghIAJAAIAQAcIAQgcIAKAAIgWAhIAXAlgApFAqIAAg+IgUA+IgIAAIgUg+IAAA+IgIAAIAAhGIAMAAIAUA9IAUg9IAMAAIAABGgAqQAqIgHgTIgbAAIgFATIgJAAIAYhGIAHAAIAZBGgAqvARIAWAAIgLgjgArrAqIAAhGIAIAAIAAA/IAeAAIAAAHgAshAqIgig6IAAA6IgIAAIAAhGIAJAAIAiA6IAAg6IAIAAIAABGgAuAAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAuaAqIAAhGIAIAAIAABGgAuwAqIgSgeIgMAAIAAAeIgIAAIAAhGIAMAAIANABIAHACQAHACACAFQADAFAAAFQAAANgPAGIATAfgAvOAFIAFAAIAJAAIAGgBQAHgDABgJQgBgIgGgDIgGgCIgKAAIgFAAgAv8AqIAAg/IgSAAIAAgHIAtAAIAAAHIgTAAIAAA/gAMNASIAAgFIAdAAIAAAFgADEgjIgLgJIgLAJIgHAAIANgOIAJAAIAOAOgAhFgjIgKgJIgLAJIgHAAIAOgOIAJAAIANAOgAthgjIgLgJIgLAJIgHAAIANgOIAJAAIAHAHIAAgFIABAAQAIAAAAgFQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgGACIAAgFQAFgCADAAQAFAAADADQAEACAAAFQAAAFgFACQgCACgGAAIAAAFIgCAAIAFAEgAqgglIgEgCIgHgDQgEAAgCAGIgEgBIACgGQACgFAGAAQADAAAFADIAEACIADABQAEAAABgGIAFABIgCAGIgEAEQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgEgBg");
	this.shape.setTransform(104,7.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0.8,207.9,12.7);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkFA7QgHgFAAgJQAAgJAGgEIAJgEQgIgEAAgEQAAgGAFgCIAIgEQgOgGAAgOQAAgMAIgGQAHgGALAAIALACIAVgBIAAAIIgOgBQAGAHAAAKQAAAKgHAFQgEAEgMACIgLADQgEACAAACQAAABAAABQAAAAABABQAAAAAAAAQABABABAAIALABIAPACQARAFAAAOQAAAMgKAFQgIAGgOAAQgQgBgJgGgAj8AjQgHADAAAGQAAAGAGADQAHAEAKAAQAMAAAGgFQAEgDAAgFQAAgMgXAAQgJAAgGADgAj4gXQgEAEAAAHQAAAGAEAEQAEAEAHAAQAHAAAEgDQAEgEAAgHQAAgHgEgDQgEgFgHgBQgGAAgFAFgAhXBBIAAgJQAKAAAFgEQADgDADgIIACgGIgYhGIALAAIATA6IAUg6IALAAIgXBBIgIAUQgIAPgSAAIgDAAgAHRA7QgBAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgEACgCQACgBADAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQACACAAAEQAAAAAAABQAAAAAAABQAAAAgBABQAAABgBAAQgCACgDAAQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBgAHEAgQgGgEgCgJIgBgMIAAgqIALAAIAAAqQAAALACAEQAEAFAIABQAKgBAFgHQADgGAAgKIAAgnIAKAAIAAAFIABAAIADgEIACgFIgBAAIgCgBQgDgCABgFQABgCACgBIAFgBQADAAACADQABAEgBAEQgCAJgMAIIAAAlIAAAHIAAAEIACAKIgKAAIgBgEIgBgGQgCAFgDACQgGAFgIAAQgJAAgGgFgAF1AdQgKgLAAgSQAAgRAKgMQAHgIALAAQAJAAAFAEQADACADAGIAAgoIALAAIAABPQAAARABAEIgKAAIgBgIIAAgCQgDAFgDACQgGAFgIAAQgMAAgHgIgAF9gWQgHAIAAAOQAAANAGAJQAFAGAIAAQAIAAAEgGQAHgJAAgNQAAgOgGgIQgFgGgIAAQgIAAgEAGgACTAgQgHgGAAgKQAAgPAQgFQAJgEASgDIAAgCQAAgIgCgCQgEgFgIAAQgOAAgCAMIgLAAQABgKAGgEQAHgHANAAQALAAAHAFQAFAEABAJIAAAJIAAAaQAAANACAGIgKAAQgBgEAAgGQgHAMgOAAQgKAAgGgFgAChADQgKAEAAAIQAAAGAEADQADAEAGAAQALAAAFgIQADgGAAgKIAAgHQgQADgGADgAmVAgQgIgGAAgKQAAgPARgFQAJgEARgDIAAgCQAAgIgCgCQgEgFgIAAQgOAAgCAMIgKAAQABgKAFgEQAHgHANAAQAMAAAGAFQAFAEABAJIABAJIAAAaQAAANACAGIgKAAQgCgEAAgGQgGAMgPAAQgJAAgGgFgAmIADQgKAEAAAIQAAAGAEADQAEAEAGAAQALAAAEgIQADgGAAgKIAAgHQgPADgHADgAAbAeQgCgDAAgDIAAgzIgKAAIAAgIIAKAAIAAgVIALAAIAAAVIARAAIAAAIIgRAAIAAAjIAAANQABAHAGAAQAGAAAFgDIAAAJQgGADgHAAQgKAAgEgHgAEqAjIAAgqIAAgJQgCgMgMAAQgJAAgFAIQgDAFAAAJIAAApIgKAAIAAgpQAAgMgCgDQgDgHgJAAQgFAAgDADQgEABgCAEQgDAFAAAKIAAAoIgLAAIAAgwIAAgPIgBgHIAKAAQABADAAAHQAHgMAOAAQAOAAAFANQAIgNAOAAQAOAAAFAJQACAEAAAHIAAAKIAAAqgABwAjIAAgnQAAgMgDgFQgDgGgJgBQgKAAgFAJQgDAFAAALIAAAmIgLAAIAAhkIALAAIAAAmQAHgKANAAQAIAAAGAEQAGADACAJIABAQIAAAogAhvAjIgegmIAeggIANAAIgeAgIAgAmgAiYAjIAAhkIALAAIAAA+IAAAmgAkmAjIAAgnQAAgMgCgFQgDgGgJgBQgKABgGAHQgDAGAAALIAAAmIgKAAIAAguIgBgSIgBgGIAKAAQABAEAAAGQAIgMAOAAQAKAAAGAFQAFAFABAIIABAOIAAAogAn1AjIAAgwIgJAAIAAgHIAJAAIAAgsIAQAAIAUABQASACAKAOQAJAOAAATQAAAUgKANQgLAOgRABIgVABgAnqAZIAIAAIAPgBQAGgBAGgDQAFgEAEgEQAHgMAAgOQAAgSgJgLQgHgJgMgCIgSAAIgFAAIAAAiIAYAAIAAAHIgYAAgAmGgtIgGgDIgEgFIgCgGIAGAAQACAFADACQADACAEAAQAEAAADgCQAEgDAAgEIAGAAQAAAEgBADIgFAEIgFADIgGABIgGgBgAg/gvIANgQIAKAAIgQAQg");
	this.shape.setTransform(39.82,11.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A7EBE").s().p("ApSB5IAAjxISlAAIAADxg");
	this.shape_1.setTransform(39.6091,11.6198,1.04,1.04);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.3,-0.9,123.8,25.099999999999998);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA2BJQAbgaAOgZQgIACgHABQgOgBgKgKQgMgOAAgTQAAgVALgNQALgNASAAQAQAAALAMQAMAMAAAXQAAAPgHAOQgHAPgPASQgQATgOALgABDgzQgFAKgBAUQABASAFALQAGAKALAAQAWAAAAglQAAgqgWAAQgLABgGAJgAIcA5QgKgKgBgTIAHAAQABAJACAGQAHANASAAQANABAIgJQAHgIAAgNQAAgTgPgHQgHgBgLAAIgDAAIAAgHIADAAQAMAAAGgFQAKgHAAgOQAAgKgFgHQgHgGgKAAQgOAAgHALQgDAFgCAIIgHAAQAEgiAiAAQAQAAAJAKQAIAIAAANQAAALgFAIQgHAHgMAEQALACAGAEQANAJAAASQAAAQgLAMQgMALgTAAQgSAAgJgKgAFBAxQgLgTABgeQAAgOACgNQADgNAGgJQAKgRAUAAQAOAAAJAHQAKAJAFASQAEAPAAARQAAAbgKAUQgKAUgWAAQgUAAgLgSgAFRgyQgJAOAAAkQAAAmAKAPQAGAIAIAAQAZAAAAg9QAAgdgGgQQgDgHgFgEQgFgFgGAAQgJAAgGALgACbA/QgDgDgBgFQABgEADgEQAEgDAEAAQAFAAADADQAEAEAAAEQAAAFgEADQgDAEgFAAQgEAAgEgEgAg3AxQgMgTABgeQAAgOACgNQADgNAGgJQAKgRAUAAQAOAAAJAHQAJAJAFASQAEAPAAARQAAAbgKAUQgJAUgWAAQgUAAgKgSgAgogyQgJAOAAAkQAAAmAKAPQAGAIAIAAQAZAAAAg9QAAgdgGgQQgDgHgFgEQgFgFgGAAQgJAAgGALgAhxA/QgDgDgBgFQABgEADgEQADgDAFAAQAFAAADADQADAEABAEQgBAFgDADQgDAEgFAAQgFAAgDgEgAjWA2QgNgMAAgWQABgUAPgWQAHgLANgOQANgNAOgMIAKAAQgcAagOAZQAIgDAGAAQAQAAAKALQAMANAAAUQAAAUgLANQgMAOgSAAQgRAAgMgNgAjLgHQgGAKAAARQAAApAYAAQALAAAHgKQAFgLAAgTQAAgSgFgKQgGgLgMAAQgNAAgFALgAnpA5QgKgKgBgTIAGAAQABAJADAGQAGANASAAQANABAJgJQAGgIABgNQAAgTgPgHQgIgBgKAAIgDAAIAAgHIADAAQALAAAHgFQAJgHAAgOQAAgKgFgHQgGgGgKAAQgOAAgIALQgDAFgBAIIgHAAQAEgiAhAAQARAAAJAKQAIAIAAANQAAALgGAIQgHAHgMAEQAMACAFAEQANAJAAASQABAQgMAMQgMALgSAAQgSAAgJgKgAGlBBIAAgLQAXgaANgSQAMgQAGgKQAFgKAAgIQAAgJgGgGQgGgGgKAAQgHAAgFADQgHAEgDAEQgDAHgCAKIgHAAQACgSAGgIQAEgGAJgEQAHgDAKAAQAPAAAIAHQAGAEADAHQADAGAAAGQAAAJgFAKQgGALgOAQIgjApIA+AAIgDAOgADMBBIAAgLQAWgaANgSQANgQAFgKQAFgKAAgIQAAgJgGgGQgGgGgKAAQgGAAgGADQgHAEgDAEQgDAHgCAKIgHAAQACgSAGgIQAFgGAHgEQAIgDAKAAQAOAAAKAHQAFAEADAHQADAGAAAGQAAAJgFAKQgGALgPAQIgiApIA9AAIgCAOgAlOBBIAAgLQAXgaANgSQAMgQAGgKQAFgKAAgIQAAgJgGgGQgGgGgKAAQgHAAgFADQgHAEgDAEQgDAHgCAKIgHAAQACgSAGgIQAEgGAJgEQAHgDAKAAQAPAAAIAHQAGAEADAHQADAGAAAGQAAAJgFAKQgGALgOAQIgjApIA+AAIgDAOgApgBBIAAgLQAXgaANgSQAMgQAGgKQAEgKAAgIQABgJgHgGQgGgGgJAAQgHAAgGADQgGAEgEAEQgDAHgBAKIgHAAQABgSAHgIQAEgGAIgEQAIgDAJAAQAPAAAJAHQAFAEAEAHQADAGAAAGQgBAJgFAKQgGALgOAQIgjApIA+AAIgCAOgAmTAQIAAgJIA0AAIAAAJg");
	this.shape.setTransform(61.9,-8.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1,-15.4,121.8,14.700000000000001);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKYBTIAAgKQALABAFgEQAGgEADgJIAHgOIgchJQgDgGgCgBQgDgCgHAAIAAgFIATABIATgBIAAAFIgHABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAAAAAIABAGIAUA2IAVg2IACgFQgBgBAAAAQAAgBAAAAQAAgBgBAAQAAAAgBAAQgCgBgGAAIAAgFIANABIARgBIAAAFIgKACQgCACgCAFIgkBcQgFALgGAFQgHAFgKAAIgDAAgApkBQQgDgEAAgEQAAgEADgEQAEgDAEAAQAFAAACADQADAEAAAEQAAAEgDAEQgCADgFAAQgEAAgEgDgAHJAoQgMgKgGgSQgEgNAAgPQAAgdANgTQAHgJALgFQAJgEALAAQARAAANALIAGgLIAEAAIAAAlIgFAAQgIgfgZAAQgTAAgIARQgJAQAAAaQAAAXAHARQAJARAUAAQAOAAAIgJQAKgKAAgRIAHAAQgBAOgFAKQgFAKgKAFQgKAFgLABQgPgBgNgIgACcAwIAAhvIgBgGQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgKgBIAAgEQAPgBANgEIAAA1QAFgHACgCQAHgHAKAAQAQAAAKAOQAJANAAATQAAAUgKANQgKANgQAAQgRAAgIgQIgIARgACqABQAAApAWABQAKAAAFgLQAGgLAAgVQAAgngVAAQgVAAgBAogABEAiQgJgNAAgUQAAgUAKgMQAKgOARAAQARAAAKAOQAJANAAATQABAUgKANQgLAOgQAAQgRAAgLgOgABQgdQgGAKABAUQgBAqAWAAQAKAAAFgKQAGgLgBgVQAAgpgUAAQgLAAgFALgAhZAnQgMgJgGgSQgEgMAAgRQAAgdANgSQAOgSAZAAQAQAAANALIAIgLIADAAIAAAlIgEAAQgDgKgEgHQgEgGgHgEQgHgEgJAAQgOAAgKAKQgNAOAAAjQAAA7AkABQAMAAAOgIIAAgfIgBgFQgBAAAAgBQAAAAAAAAQgBgBAAAAQgBAAgBAAIgKgCIAAgFIAVABIAWgBIAAAFQgJAAgCACQgDACAAAFIAAAeQgVAOgUAAQgRAAgNgJgAjtAjQgKgNAAgVQAAgUAKgNQAKgNARAAQALAAAIAHQAIAFAEALQADAJABANIg5AAQABARADAJQAFAPAQABQAKgBAGgGQAGgGACgMIAIAAQgCALgGAHQgJANgSAAQgRAAgKgNgAjngHIAoAAQgCghgRABQgTgBgCAhgAJnAqQgEgEgBgFQgBgGAAgKIAAg1IgLAAIAAgGQARAAAFgcIAFAAIAAAbIAWAAIAAAHIgWAAIAAA2QAAAMABAEQADAGAHAAQAFAAAHgEIAAAGQgJAGgJgBQgLAAgEgFgAEtArQgEgDgBgJQgEAHgDADQgHAHgLgBQgMABgHgHQgIgHABgKQAAgSAVgIQAMgFAQgCIAAgLQAAgKgDgEQgEgGgJABQgGgBgFAEQgFADABAFIAAABIAAADQAAAIgIAAQgGAAgBgFQABgJAIgHQAJgHAOgBQAIAAAGADQAHAEADAEQAGAHAAAOIAAAmQgBAKACADQACADAEABIAEgBIAAAFIgKABQgHAAgDgEgAERABQgNAHgBAOQABAIAEAFQAEAFAIAAQAJAAAFgHQAEgHAAgPIAAgPQgNACgIADgApIArQgDgDAAgJQgEAHgEADQgHAHgLgBQgMABgHgHQgIgHAAgKQABgSAVgIQAMgFAQgCIAAgLQAAgKgDgEQgEgGgJABQgGgBgFAEQgEADgBAFIAAABIAAADQAAAIgHAAQgHAAABgFQgBgJAJgHQAKgHANgBQAHAAAIADQAGAEAEAEQAEAHAAAOIAAAmQAAAKACADQABADAEABIAGgBIAAAFIgLABQgHAAgEgEgApkABQgNAHABAOQAAAIAEAFQAEAFAIAAQAJAAAEgHQAFgHAAgPIAAgPQgNACgJADgAI2AtIgVABIAAgDQAIgBADgBQACgCAAgGIAAg8IgBgHIgDgDIgJAAIAAgEQAPgBANgEIAABPIABAFQABABAAAAQAAABAAAAQABABAAAAQABAAABABIAJABIAAADIgVgBgAFgAtIgVABIAAgDQAIgBADgBQADgCAAgGIAAhgIgBgGQgBgBAAAAQAAgBAAAAQgBgBAAAAQgBAAgBAAIgJgBIAAgEQAPgBANgEIAABzIABAFIAEAEIAJABIAAADIgVgBgAAZAtIgUABIAAgDQAIgBACgBQADgCAAgGIAAhgIgBgGQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAIgJgBIAAgEQAPgBANgEIAABzIABAFIADAEIAKABIAAADIgWgBgAkYAtIgUABIAAgDQAHgBACgBQADgCAAgGIAAgtQAAgMgDgEQgEgIgKAAQgKAAgGAIQgDAFgBALIAAAtIABAFIADAEIAJABIAAADIgVgBIgUABIAAgDQAIgBACgBQADgCAAgGIAAhgIgBgGQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBAAIgJgBIAAgEQAPgBANgEIAAAyQAKgNAPAAQAPABAHALQAGAIgBANIAAAtIABAFQAAABABAAQAAABAAAAQABABAAAAQABAAAAABIAKABIAAADIgVgBgAmYAtIgYABIAAgEQAIgBADgBQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBIABgIIAAhnIgKAAQgMAAgFAIQgDAFgEAKIgEAAIAEgdIBUAAIAFAdIgEAAQgEgOgFgEQgFgFgJAAIgMAAIAABnIABAIQAAABAAAAQABAAAAABQABAAAAAAQABABAAAAQAEABAIABIAAAEIgYgBgAoUAtIgVABIAAgDQAJgBACgBQADgCAAgGIAAg8IgBgHIgDgDIgJAAIAAgEQAPgBANgEIAABPIABAFQAAABAAAAQABABAAAAQAAABABAAQAAAAABABIAKABIAAADIgWgBgAq5AtIgZABIAAgEQAJgBACgBQAEgBABgCIABgIIAAhnIgLAAQgLAAgGAIQgDAFgEAKIgEAAIAFgdIBTAAIAFAdIgEAAQgEgOgEgEQgFgFgJAAIgMAAIAABnIABAIQAAABAAAAQAAAAABABQAAAAABAAQAAABABAAQADABAIABIAAAEIgXgBgAIug+QgDgDAAgFQAAgEADgDQADgDAEAAQAFAAADADQACADAAAEQAAAFgCADQgDADgFAAQgEAAgDgDgAocg+QgCgDAAgFQAAgEACgDQAEgDADAAQAFAAADADQADADAAAEQAAAFgDADQgDADgFAAQgDAAgEgDg");
	this.shape.setTransform(174.5,65.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(100,57.6,149,16.6);


(lib.Symbol17_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance_1 = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol24("synched",0);
	this.instance.setTransform(103.45,10.6,1.5,1.5,0,0,0,103.5,10.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.95,scaleY:0.95,x:103.5,alpha:1},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(831).to({startPosition:0},0).to({_off:true},1).wait(2196));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-140.8,-11.7,459.2,46.8);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol19("synched",0);
	this.instance.setTransform(98.8,43.05,1.5,1.5,0,0,0,98.8,9.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.95,scaleY:0.95,y:6.55,alpha:1},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:9.8},10,cjs.Ease.get(1)).wait(305).to({startPosition:0},0).to({_off:true},1).wait(2024));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-146.4,-85.8,459,45.599999999999994);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol16("synched",0);
	this.instance.setTransform(334.65,86.25,0.4,0.4,0,0,0,334.7,86.3);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:334.6,scaleX:1.1,scaleY:1.1,x:334.6,y:86.35,alpha:1},8,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:86.3},7,cjs.Ease.get(1)).wait(267).to({startPosition:0},0).to({_off:true},1).wait(257));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-187.4,-43.7,1067,275);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol15("synched",0);
	this.instance.setTransform(103.8,-18,1,1,0,0,0,103.8,7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:9,alpha:1},8,cjs.Ease.get(1)).to({y:7},5,cjs.Ease.get(1)).wait(276).to({startPosition:0},0).to({_off:true},1).wait(150));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,-24.2,207.9,39.7);


(lib.Symbol11copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.setTransform(43.4,7.6,1,1,0,0,0,43.4,7.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.9,scaleY:0.9},9,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.3,-1,123.8,25.2);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.setTransform(43.4,7.6,1,1,0,0,0,43.4,7.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14,cjs.Ease.get(1)).wait(12).to({startPosition:0},0).to({_off:true},1).wait(1938));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.3,-0.9,123.8,25.099999999999998);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_6
	this.instance = new lib.Symbol10("synched",0);
	this.instance.setTransform(71.4,186.45,1,1,0,0,0,120.6,10.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:156.4,alpha:1},8,cjs.Ease.quadOut).wait(262).to({startPosition:0},0).to({_off:true},1).wait(4023));

	// Layer_4
	this.instance_1 = new lib.Symbol8("synched",0);
	this.instance_1.setTransform(211,116.9,1,1,0,0,0,66.5,13.3);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:128,alpha:1},8,cjs.Ease.quadOut).wait(262).to({startPosition:0},0).to({_off:true},1).wait(4023));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.2,138.2,441.7,39.60000000000002);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4
	this.instance = new lib.Symbol23("synched",0);
	this.instance.setTransform(-296.5,91.6,1,1,0,0,0,103.5,10.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(119).to({_off:false},0).wait(51).to({startPosition:51},0).to({_off:true},1).wait(800));

	// Layer_2
	this.instance_1 = new lib.Symbol22("synched",0);
	this.instance_1.setTransform(180.6,60.15,2,2,0,0,0,107.5,49.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(99).to({_off:false},0).to({regY:49,scaleX:1,scaleY:1,x:90.5,y:60,alpha:1},18,cjs.Ease.get(1)).wait(53).to({startPosition:0},0).to({_off:true},1).wait(800));

	// Layer_11
	this.instance_2 = new lib.Symbol18("synched",0);
	this.instance_2.setTransform(-296.2,164.8,1,1,0,0,0,98.8,9.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).wait(80).to({startPosition:80},0).to({alpha:0,startPosition:81},14,cjs.Ease.get(1)).wait(57).to({startPosition:138},0).to({_off:true},1).wait(800));

	// Layer_1
	this.instance_3 = new lib.Symbol21("synched",0);
	this.instance_3.setTransform(83.05,86.5,2,2,0,0,0,83,86.5);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({scaleX:1,scaleY:1,x:83,alpha:1},17,cjs.Ease.get(1)).wait(82).to({startPosition:0},0).to({alpha:0},14,cjs.Ease.get(1)).wait(57).to({startPosition:0},0).to({_off:true},1).wait(188).to({_off:false},0).wait(612));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-566,-170.4,1232.7,520.4);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_289 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(289).call(this.frame_289).wait(1));

	// cta copy
	this.instance = new lib.Symbol11copy();
	this.instance.setTransform(489.6,208.7,1,1,0,0,0,43.6,7.7);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(68).to({_off:false},0).wait(51).to({x:263.6,y:183.7},18,cjs.Ease.get(1)).wait(153));

	// cta
	this.instance_1 = new lib.Symbol11("synched",0);
	this.instance_1.setTransform(489.6,208.8,1,1,0,0,0,43.6,7.8);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41).to({_off:false},0).to({_off:true},27).wait(222));

	// logo copy
	this.instance_2 = new lib.Logo();
	this.instance_2.setTransform(824,191,0.51,0.51);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(290));

	// Layer_7
	this.instance_3 = new lib.Symbol20("synched",0);
	this.instance_3.setTransform(649,131.5,1,1,0,0,0,83,86.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(119).to({_off:false},0).wait(171));

	// Layer_9
	this.instance_4 = new lib.Symbol14("synched",0);
	this.instance_4.setTransform(481.95,118.15,1.01,1.01,0,0,0,334.6,86.3);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(7).to({_off:false},0).wait(112).to({startPosition:112},0).to({regX:334.7,regY:86.4,scaleX:0.72,scaleY:0.72,x:255.95,y:94.2,startPosition:130},18,cjs.Ease.get(1)).wait(153));

	// Layer_8 copy
	this.instance_5 = new lib.Symbol17_1("synched",0);
	this.instance_5.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(119).to({_off:false},0).to({alpha:1},11,cjs.Ease.get(1)).wait(160));

	// Layer_6
	this.instance_6 = new lib.Symbol13("synched",0);
	this.instance_6.setTransform(488.8,36.45,1.45,1.45,0,0,0,104,7.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(290));

	// Layer_5
	this.instance_7 = new lib.Symbol5("synched",0);
	this.instance_7.setTransform(371.1,54.95,1.1,1.1,0,0,0,62.8,63.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(19).to({_off:false},0).wait(271));

	// Layer_8
	this.instance_8 = new lib.Symbol17("synched",0);
	this.instance_8.setTransform(485,125,1,1,0,0,0,485,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(290));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85.7,-125.4,1318.3,520.4);


// stage content:
(lib._970x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(485,115.9,485,140.49999999999997);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 970,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1694524513270", id:"bg"},
		{src:"images/h2.png?1694524513270", id:"h2"},
		{src:"images/h3.png?1694524513270", id:"h3"},
		{src:"images/light.png?1694524513270", id:"light"},
		{src:"images/Logo.png?1694524513270", id:"Logo"},
		{src:"images/tagline.png?1694524513270", id:"tagline"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;