(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.h2 = function() {
	this.initialize(img.h2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,332,356);


(lib.h3 = function() {
	this.initialize(img.h3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,579,283);


(lib.light = function() {
	this.initialize(img.light);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.Logo = function() {
	this.initialize(img.Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,154,117);


(lib.Rectangl = function() {
	this.initialize(img.Rectangl);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,115);


(lib.tagline = function() {
	this.initialize(img.tagline);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,750,185);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3E8DCA").s().p("AKJBhQgDgDAAgFQAAgFADgDQACgEAEAAQADAAADAEQACADABAFQgBAFgCADQgDADgDAAQgEAAgCgDgAmSBhQgDgDAAgFQAAgFADgDQACgEAEAAQADAAADAEQACADAAAFQAAAFgCADQgDADgDAAQgEAAgCgDgApdBhQgHgDgEgHQgEgFAAgIQAAgIADgFQAEgFAHgDQgEgDgCgDQgCgCAAgEQAAgFAFgEQADgEAJgDQgJgDgEgHQgFgHAAgKQAAgOAHgHQAIgIAMAAIAJABIAHAEIAUAAIAAAIIgPgBQADAEAAAEIABAJQAAAGgCAGQgDAGgFAEIgDADIgFACIgIADIgKADQgDACgBACIgCADIABADQAAABABAAQAAAAABABQAAAAABAAQABAAABAAIAIABIALACIAIABIAFACQAGADACAFQAEAGAAAHQAAAJgFAHQgEAHgHADQgIAEgKAAQgJAAgHgDgApgA/QgGAEAAAIQAAAGAEAEQACAEAGADQAGACAHAAQALAAAHgFQAGgFAAgJQAAgIgGgEQgHgFgMAAQgMAAgGAFgApXgUQgEAHAAALQAAALAEAGQADAGAHAAQAHAAAEgGQAEgGAAgLQAAgMgEgGQgDgGgHAAQgHAAgEAGgAPSBAIgHgBQgDgBgCgDIgIgHQgFAGgFADQgHADgHAAQgNAAgJgIQgJgJgFgPQgFgPAAgUQAAgUAFgPQAFgPAJgIQAJgIANgBQAMABAJAIQAJAIAFAPQAFAPAAAVQAAALgCAKQgCALgDAJQAFALAEAFQADAEAFAAIAAAFgAOSgwQgHAQAAAdQAAAdAHAQQAHAQANABQANgBAHgPQAHgQAAgdQAAgegHgQQgHgQgNAAQgNAAgHAQgAILA6QgGgGgEgLQgDgLAAgNQAAgPADgKQAEgKAGgGQAGgGAIAAQAGAAAEADQAEADAEAJIAAgZIgRAAIAAgHIARAAIAAgDQABgHgDgCQgCgCgGAAIAAgDIAMgCIALgDIAAAWIAKAAIAAAHIgKAAIAABTIAAAJQAAAAABABQAAAAAAABQABAAAAABQABAAAAAAIAHABIAAADIgIABIgFABIgGACIgCgHIAAgIQgEAIgEAEQgFAEgGAAQgIAAgHgGgAIKAQQAAAVAFALQAEAKAIABQAIgBAEgKQAFgKAAgUQAAgVgFgLQgEgLgIAAQgRAAAAApgAg2A6QgHgGgEgLQgDgKAAgPQAAgOADgKQAEgLAHgGQAHgGAJAAQAFgBADACQAEACADAFIAEgKIADAAIAAAgIgDAAIgCgIIgCgGQgCgFgEgDQgEgDgEAAQgJAAgEALQgFAMAAATQAAAVAEAKQAFAKAIAAQAPAAADgZIAFAAQgBAPgGAJQgGAIgLAAQgIAAgHgGgAi8A6QgGgGgEgLQgEgKAAgPQAAgOAEgKQAEgLAGgGQAIgGAIAAQAFgBAEACQADACAEAFIAEgKIACAAIAAAgIgDAAIgBgIIgDgGQgCgFgDgDQgEgDgFAAQgIAAgFALQgFAMAAATQAAAVAFAKQAEAKAJAAQAOAAADgZIAGAAQgCAPgGAJQgGAIgKAAQgJAAgHgGgAJ6AzQgIgNAAgWQAAgPAEgKQAEgKAGgGQAHgGAJAAQANAAAHAMQAHALAAAWIgtAAIABAQIACALQACAIAEAEQAFAEAGAAQAIAAAFgGQAFgHACgMIAFAAQgBAPgHAIQgHAJgMAAQgOAAgIgNgAKfAHQAAgQgEgJQgEgIgIAAQgHAAgEAIQgEAJgBAQIAgAAIAAAAgAGeAzQgIgNAAgWQAAgPADgKQAEgKAHgGQAGgGAJAAQANAAAHAMQAIALAAAWIgtAAIAAAQIADALQACAIAEAEQAFAEAGAAQAIAAAFgGQAFgHABgMIAGAAQgBAPgHAIQgIAJgLAAQgOAAgIgNgAHDAHQgBgQgEgJQgDgIgIAAQgHAAgEAIQgFAJgBAQIAhAAIAAAAgAEOA4IgBgKQgDAJgFAEQgFAFgHgBQgGAAgFgDQgFgCgDgFIgDgJIAAgNIAAgrQAAgHgCgDQgDgCgGAAIAAgEIALgBIALgDIAAA/QAAANAEAFQADAGAHAAQAIAAAEgHQAEgGAAgOIAAgoQAAgHgCgDQgCgCgHAAIAAgEIAMgBIALgDIAABOIABAGQAAAAAAABQABAAAAABQABAAAAAAQABABAAAAIAHAAIAAAEIgLACIgKADIAAgIgACcA4QgFgGAAgMQAAgJADgGQAFgHAJgEQAFgDAFgCIAMgCIAAgLIgBgJQAAgDgBgCQgCgDgCgBIgGgCQgGAAgDADQgEAEAAAEIAAABIAAAEIAAABQAAAEgCACQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBgCAAgDQAAgGADgFQAEgGAFgDQAGgDAHAAQAGAAAFADQAGADADAFIACAJIABALIAAAoQAAAKACAEQABADADAAIACAAIACAAIAAAFIgEABIgEAAQgGAAgDgEQgDgDAAgJQgEAJgFAEQgEAEgIAAQgJgBgGgHgACpATQgHAHAAALQABAJADAEQADAFAGAAQAIAAAEgHQADgHAAgOIAAgSQgOAEgHAGgAiEA4QgFgGAAgMQAAgJAEgGQAEgHAJgEIAKgFIAMgCIAAgLIAAgJQgBgDgBgCQgCgDgCgBQgDgCgDAAQgGAAgDADQgEAEAAAEIAAABIAAAEIAAABQAAAEgBACQgCACgDAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBIgBgFQAAgGADgFQAEgGAFgDQAGgDAHAAQAGAAAGADQAFADADAFQACADABAGIABALIAAAoIABAOQABADADAAIACAAIACAAIAAAFIgEABIgEAAQgGAAgDgEQgCgDgBgJQgEAJgEAEQgFAEgHAAQgKgBgGgHgAh3ATQgGAHAAALQAAAJADAEQADAFAGAAQAIAAAEgHQADgHAAgOIAAgSQgOAEgHAGgAmhAzQgIgNAAgWQAAgPAEgKQADgKAHgGQAHgGAJAAQANAAAHAMQAHALAAAWIgtAAIABAQIACALQACAIAEAEQAFAEAGAAQAIAAAFgGQAFgHACgMIAFAAQgBAPgHAIQgHAJgMAAQgOAAgIgNgAl8AHQAAgQgEgJQgEgIgIAAQgHAAgEAIQgEAJgBAQIAgAAIAAAAgAtHA4QgGgGAAgMQAAgJAEgGQAEgHAJgEQAFgDAGgCIALgCIAAgLIAAgJIgCgFQgBgDgDgBIgGgCQgGAAgDAEQgEADAAAFIAAABIAAACIABACQAAAEgCACQgCACgDAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQgCgCAAgDQAAgGAEgFQADgGAGgDQAFgDAHAAQAHAAAFADQAFADADAFQACADABAGIABALIAAAoQAAAKABAEQABADADAAIACAAIACAAIAAAFIgEABIgEAAQgGAAgCgEQgDgDgBgJQgDAJgFAEQgFAEgHAAQgKgBgFgHgAs6ATQgHAHAAALQAAAJADAEQAEAFAGAAQAHAAAEgHQADgHAAgPIAAgRQgOAEgGAGgAL3A9IgIAAIgHAAIgJABIAAgEQAFAAADgCQACgCAAgGIAAgwIgBgJIgCgGQgBgEgDgBQgDgCgEAAQgEAAgDACQgDACgCAEQgCADgBADIgBAJIAAAvQAAAGACACQADACAFAAIAAAEIgJgBIgHAAIgHAAIgKABIAAgEQAHAAACgCQACgCAAgGIAAg7IAAgIQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAIgIAAIAAgEIAMgCIAIgEIABAHIABAKQAEgIAFgEQAFgDAHAAQAFAAAFADQAFADADAGIADAJIABALIAAAvQAAAGACACQACACAHAAIAAAEIgJgBgAJgA9IgHAAIgHAAIgKABIAAgEQAHAAACgCQACgCAAgGIAAg9QAAgHgCgCQgCgCgHAAIAAgEIAMgBIALgDIAABQQAAAGACACQACACAHAAIAAAEIgKgBgAGLA9IgHAAIgIAAIgJABIAAgEIAGgBQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBIAAgCIgCgDIgMgbIgOAZIgCAFIgBACQAAABAAAAQABABAAAAQAAAAAAAAQABABAAAAQACABAFAAIAAAEIgHAAIgDAAIgDAAIgDAAIgDAAIgHAAIAAgEQAEAAACgBQADgBABgCIAFgHIAQgeIgPgjQgCgEgDgCQgDgCgFAAIAAgEIAJABIAHAAIAHAAIAJgBIAAAEIgGABIgBADIAAACIABADIAKAUIALgUIACgDIABgCQAAAAAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAIgGgBIAAgEIAHABIAFAAIAFAAIAHgBIAAAEIgFABIgEADIgDAEIgPAbIASAnIADAHQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAIAGABIAAAEIgJgBgACFA9IgHAAIgHAAIgJABIAAgEQAFAAADgCQACgCAAgGIAAgxQAAgLgDgFQgDgFgHAAQgHAAgEAGQgEAGAAAKIAAAwQAAAGACACQACACAGAAIAAAEIgIgBIgIAAIgHAAIgJABIAAgEQAGAAACgCQACgCAAgGIAAgwIAAgJIgCgGIgEgFQgCgCgEAAQgEAAgDACQgEACgCAFIgCAGIAAAJIAAAuQAAAGACACQACACAGAAIAAAEIgJgBIgIAAIgHAAIgKABIAAgEQAIAAABgCQADgCgBgGIAAg7IAAgIIgBgCIgCgCIgHAAIAAgEIALgCIAJgEIABAIIAAAJQAFgIAEgEQAFgDAHAAQAHAAAEADQAFAEACAIQAEgIAFgEQAFgDAHAAQAGAAAFADQAFADACAGIACAIIABALIAAAwQAAAGACACQACACAHAAIAAAEIgKgBgAj/A9IgHAAIgIAAIgJABIAAgEQAGAAACgCQADgCgBgGIAAgxQAAgLgDgFQgDgFgGAAQgHAAgFAGQgDAGAAAKIAAAwQAAAGACACQACACAGAAIAAAEIgJgBIgHAAIgHAAIgJABIAAgEQAFAAADgCQACgCAAgGIAAgwIgBgJIgBgGIgEgFQgDgCgEAAQgDAAgEACQgDACgCAFIgCAGIgBAJIAAAuQAAAGACACQACACAGAAIAAAEIgJgBIgHAAIgIAAIgJABIAAgEQAHAAACgCQACgCAAgGIAAg7IAAgIIgBgCIgCgCIgIAAIAAgEIAMgCIAIgEIABAIIABAJQAEgIAFgEQAFgDAGAAQAHAAAFADQAEAEADAIQAEgIAFgEQAEgDAIAAQAGAAAFADQAEADADAGIACAIIABALIAAAwQgBAGACACQACACAHAAIAAAEIgJgBgAm7A9IgHAAIgHAAIgKABIAAgEQAHAAACgCQACgCAAgGIAAg9QAAgHgCgCQgCgCgHAAIAAgEIAMgBIALgDIAABQQAAAGACACQACACAHAAIAAAEIgKgBgAniA9IgIAAIgHAAIgJABIAAgEQAGAAACgCQACgCAAgGIAAgwIgBgJIgBgGQgCgEgDgBQgDgCgEAAQgDAAgEACQgDACgCAEQgCADgBADIAAAJIAAAvQgBAGADACQABACAGAAIAAAEIgJgBIgHAAIgIAAIgJABIAAgEQAHAAACgCQADgCgBgGIAAhhQABgIgDgCQgBgCgIAAIAAgDIAMgCIAMgDIAAAzQADgHAFgDQAEgDAHAAQAGAAAFADQAEADADAGQACAEABAFIABALIAAAvQAAAGACACQACACAHAAIAAAEIgJgBgAp7A9IgIAAIgHAAIgJABIAAgEQAGAAACgCQACgCAAgGIAAgwIAAgJIgCgGQgCgEgDgBQgCgCgEAAQgEAAgEACQgDACgCAEQgCADAAADIgBAJIAAAvQAAAGACACQACACAGAAIAAAEIgJgBIgHAAIgIAAIgJABIAAgEQAHAAABgCQADgCAAgGIAAg7IgBgIQAAgBAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAIgHAAIAAgEIALgCIAJgEIABAHIAAAKQAFgIAFgEQAFgDAGAAQAGAAAFADQAEADAEAGIADAJIABALIAAAvQgBAGACACQACACAHAAIAAAEIgJgBgArxA9IgIAAIgHAAIgKABIAAgEQAHAAACgCQACgCAAgGIAAg9QAAgHgCgCQgCgCgHAAIAAgEIAMgBIALgDIAABQQAAAGACACQADACAGAAIAAAEIgJgBgAtuA9IgHAAIgIAAIgJABIAAgEQAGAAADgCQACgCgBgGIAAg8QABgGgBgCQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAgBgBAAIgHAAIAAgEIALgBIAJgDIAAAGIABAGIAAAGQADgIAEgFQAFgEAGAAQAGAAADAEQAEAEAAAHQAAAFgCACQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAQgDAAgCgBQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAgBIABgBIAAgDIAAgCQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAAAAAQgBAAAAAAQgGAAgEAIQgDAIAAAOIAAApQgBAGADACQACACAHAAIAAAEIgKgBgAupA9IgJAAIgIAAIgLABIAAgFIAIgBQADgBABgDQABgDAAgEIAAhqIgIAAQgGAAgDACQgDACgDAFQgCAFgCAJIgEAAIAFgdIBCAAIAEAdIgEAAQgBgJgDgFQgCgFgDgCQgDgCgGAAIgJAAIAABqQgBAEABADQABADADABIAIABIAAAFIgKgBgAMqA+IAAgFIAIgBQADgBABgDIABgIIAAhdIgBgIQgBgDgDgBIgIgBIAAgFIBCAAIADAdIgEAAQgCgNgEgGQgEgEgIAAIgWAAIAAA1IAWAAQAFABACgEQACgDAAgKIAEAAIAAAlIgEAAQAAgJgCgEQgCgCgGAAIgVAAIAAAuQAAAHACACQACADAGAAIALAAQAGAAAEgCQAEgCADgGIAEgQIAEAAIgEAggAs2gsIAAgMIAGgBIADgBIABgBIACgCIABgEQAAgDgCgCQgDgCgDAAIgDABIgFACIgCgHIAHgCIAGgBQAHAAAEAEQAEAEAAAHQAAAGgDADQgEADgFAAIgCAAIgDAAIAAAIgAKggtIgQgQIgRAQIgHAAIAUgcIAHAAIAUAcgADEgtIgRgQIgQAQIgHAAIAUgcIAHAAIAUAcgAh1gtIAPgcIARAAIgZAcgAl7gtIgQgQIgRAQIgHAAIAUgcIAHAAIAUAcgAJTgxQgDgDAAgFQAAgEADgDQACgDADAAQAEAAACADQACADAAAEQAAAFgCADQgCADgEAAQgDAAgCgDgAnIgxQgDgDAAgFQAAgEADgDQABgDAEAAQAEAAACADQACADAAAEQAAAFgCADQgCADgEAAQgEAAgBgDgAr/gxQgCgDAAgFQAAgEACgDQACgDAEAAQADAAACADQADADAAAEQAAAFgDADQgCADgEAAQgDAAgCgDgAC6hNIgEgCIgFgFIgEgDIgDgBQgEAAgCACQgCACgBAGIgFgCIADgJIACgFIAEgEIAFgBIAEAAIAEADIAGAFIADACIADABQAEAAACgCQACgCABgGIAEABIgBAJIgDAGIgFAEIgFABIgDAAg");
	this.shape.setTransform(103.225,12.575);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.9,2.6,196.7,20);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.h3();
	this.instance.setTransform(-42,9,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-42,9,289.5,141.5);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.h2();
	this.instance.setTransform(-4,1,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,1,166,178);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3E8DCA").s().p("AosBgIgIAAIgIAAIgJABIAAgEQAHAAACgCQACgDAAgGIAAhpQAAgFgBgCQgBgEgCgBIgHAAIAAgEIAIgBIAGgBIAGgBIABAHIACAKQADgJAFgEQAFgEAGAAQAJAAAGAHQAHAGAEALQAEAMAAAOQAAAPgEALQgEALgGAHQgHAGgIAAQgHAAgEgDQgEgEgEgJIAAAoQgBAGADADQACACAHAAIAAAEIgKgBgAopgZQgFALABAUQgBAXAFAMQAEALAKAAQAIAAAEgLQAFgLAAgWQAAgVgFgMQgEgLgJAAQgJAAgEALgAGaBdQgIgDgDgHQgEgGgBgJQAAgHAEgGQADgFAIgEQgEgCgCgDQgCgCgBgFQABgFAEgFQAFgEAHgCQgHgEgFgHQgFgHAAgLQAAgOAHgJQAIgIAMAAIAJABQAEABAEADIAUAAIAAAIIgOAAIACAJIABAIQAAAIgCAGQgCAGgGAFIgDACIgGADIgIACIgKAEQgEABgBADIgBADQAAAAAAABQAAABAAAAQAAABABAAQAAAAAAAAQAAABABAAQAAAAAAAAQABABABAAQAAAAABAAIAKACIAKABIAIACIAGACQAGADADAGQACAGABAHQAAAKgFAHQgDAHgJAEQgHAEgKAAQgKAAgHgEgAGXA5QgHAFAAAIQABAGADAFQADAEAGADQAHACAGAAQAMAAAGgFQAHgFAAgKQAAgIgHgFQgGgEgNAAQgMAAgGAEgAGggeQgEAGgBANQABALAEAHQAEAHAGAAQAIAAADgHQAFgHAAgMQAAgMgFgGQgDgHgHAAQgHAAgEAHgAEPBdQgDgDgBgFQABgFADgDQACgEAEAAQADAAADAEQACADAAAFQAAAFgCADQgDAEgDAAQgEAAgCgEgAOOAyQgKgJgFgQQgFgQAAgVQAAgWAFgPQAFgQAKgJQAKgIAMAAQAHAAAHADQAFACAGAHIAHgNIACAAIAAApIgDAAIgDgLIgDgHQgDgIgGgEQgGgEgHAAQgPAAgJAQQgHAQAAAgQAAAfAHARQAIAQAPABQAFAAAGgCIAKgGIAAgjQAAgGgCgCQgDgCgGAAIAAgEIAKABIAGAAIAIAAIAKgBIAAAEIgHABQgBAAAAAAQgBABAAAAQAAAAgBABQAAAAAAABIgBAGIAAAiQgKAIgIADQgIADgJAAQgMAAgKgIgAJEA0QgHgGgEgMQgDgLAAgPQAAgPADgLQAFgMAGgGQAIgGAJAAQAIAAAIAGQAHAHAEAMIACgGIABgHIgBAAIgBAAQgDAAgCgCQgCgDAAgDQAAgFACgDQADgCADAAQAEAAACADQADADgBAHQABAEgCADIgCAIIgGALIAAAAIABAIIAAAIQABAPgEAMQgFALgFAHQgIAGgJAAQgJAAgHgGgAJHgZQgFALAAAWQAAAWAFAMQAEALAJAAQAJAAAEgLQAEgMABgWQgBgWgEgLQgEgMgJAAQgIAAgFAMgAIEA0QgGgGgEgMQgDgKAAgQQAAgOADgMQAEgMAHgGQAHgGAKAAQAEgBAEACQAEACADAFIAEgLIADAAIAAAjIgDAAIgCgJIgCgGQgCgGgEgDQgFgDgEAAQgJAAgEAMQgFAMAAAVQAAAWAFALQAEALAJAAQAPAAACgcIAHAAQgCARgGAJQgHAIgKAAQgJAAgIgGgAEFA0QgHgGgDgMQgFgLAAgPQAAgPAFgLQADgMAIgGQAGgGAKAAQAIAAAHAGQAHAGAEAMQADALAAAPQAAAPgEALQgEALgHAHQgGAGgJAAQgJAAgHgGgAEIgZQgFALAAAWQAAAWAFAMQAEALAIAAQAKAAAEgLQAFgMgBgWQABgWgFgLQgEgMgJAAQgJAAgEAMgAC4A0QgGgGgEgMQgEgLABgPQgBgOAEgLQAEgMAGgGQAHgGAJAAQAFAAAEADQAFADAEAKIAAgbIgSAAIAAgHIASAAIAAgDQAAgHgCgCQgCgDgHAAIAAgDIAMgCIALgDIAAAXIALAAIAAAHIgLAAIAABZQAAAFABADQABADADABIAHABIAAADIgIACIgHABIgGACIgCgIIAAgIQgDAIgFAFQgFADgGAAQgJAAgHgGgAC3AIQAAAWAFALQAEAMAJAAQAIAAAEgLQAFgLAAgWQAAgVgFgMQgEgLgJAAQgQAAgBArgABOAsQgIgNgBgYQABgOAEgLQADgMAHgGQAHgGAKAAQAMAAAIAMQAHANAAAWIguAAIABASQAAAGACAFQADAJAEAEQAFAEAGAAQAIAAAFgHQAFgGACgOIAGAAQgBAQgIAJQgHAJgMAAQgPAAgIgOgAB0gBQgBgSgDgJQgEgJgIAAQgIAAgEAJQgFAJAAASIAhAAIAAAAgAhHA3QgDgDgDgFIgBgIIgBgLIABg8IgKAAIAAgHQAHAAAEgIQAFgHADgPIADAAIAAAdIATAAIAAAIIgTAAIAAA6QAAAOABAFQAEAFAEAAIAFgBIAGgDIAAAGQgEADgEACQgEABgDAAQgGAAgEgDgAiRAsQgJgNABgYQAAgOAEgLQADgMAHgGQAHgGAJAAQANAAAIAMQAHANAAAWIguAAIABASIABALQADAJAEAEQAFAEAGAAQAJAAAFgHQAFgGABgOIAHAAQgBAQgJAJQgGAJgNAAQgOAAgIgOgAhrgBQAAgSgFgJQgEgJgHAAQgIAAgEAJQgEAJgCASIAiAAIAAAAgAkvA3QgEgDgDgFIgBgIIgBgLIABg8IgKAAIAAgHQAHAAAFgIQAFgHACgPIAEAAIAAAdIASAAIAAAIIgSAAIgBA6QAAAOACAFQADAFAFAAIAEgBIAGgDIAAAGQgDADgFACIgHABQgGAAgDgDgAmgAzQgFgHgBgNQAAgJAEgHQAFgHAJgFIALgEIAMgCIAAgMIAAgKQAAgDgDgCQgBgEgCgBIgGgBQgGAAgEADQgEADAAAFIAAABIAAAEQAAAFgBACQgCADgDAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBgBAAAAIgBgGQAAgGAEgGQADgFAGgDQAGgEAHAAQAGAAAFADQAGADADAGIADAJIABANIAAApQgBALACAEQABAEAEAAIACgBIACAAIAAAFIgFABIgEABQgFAAgDgFQgDgDgBgKQgDAKgFAEQgGAEgIAAQgJAAgGgHgAmSAMQgHAHAAALQAAAJADAFQAEAFAGAAQAJAAADgHQADgHAAgQIAAgSQgOADgHAIgAsbAzQgHgHAAgNQAAgJAFgHQAEgHAKgFIALgEIALgCIAAgMIAAgKIgCgFQgCgEgCgBIgGgBQgFAAgEADQgFADAAAFIAAABIAAAEIgBAHQgBADgDAAQgDAAgCgCIAAgGQAAgGADgGQADgFAGgDQAGgEAHAAQAGAAAGADQAFADADAGQACADABAGIACANIAAApQgBALABAEQACAEADAAIACgBIADAAIAAAFIgGABIgEABQgGAAgCgFQgDgDgBgKQgDAKgFAEQgFAEgIAAQgJAAgGgHgAsOAMQgGAHgBALQAAAJADAFQAEAFAGAAQAJAAADgHQADgHAAgQIAAgSQgOADgHAIgANqA4IgGgBIgFAAIgIABIgMABIAAgFQAHgBACgCQAEgCAAgFIgBhuIgaBbIgCAIIgDAGIgCAIIgBAHIgDAAIghh4IgEBsQAAAGADACQADADAHABIAAAFIgIgBIgHAAIgGAAIgKABIAAgFIAIgCQADgBABgDIABgIIADhlQAAgHgCgDQgDgCgHAAIAAgGIAHABIAFAAIAHAAIAIgBIAdBnIAdhnIAJABIAHAAIAGAAIAGgBIAAAFQgHABgDACQgDADAAAGIACBmQAAAGABACQABACADACIAIACIAAAFIgIgBgALvA4IgJgBIgJABIgKABIAAgFQAFgBADgBQABgBAAAAQABgBAAAAQAAAAAAgBQAAgBAAAAIAAgEIgBgDIgGgWIgkAAIgEATIgCAFIAAAEQAAADACACIAHACIAAAFIgHgBIgIAAIgGAAIgJABIAAgFQAGAAACgCQADgBACgDIADgJIAjh5IAhB7QABAFABADIAEADIAIACIAAAFIgKgBgALVAKIgPg+IgSA+IAhAAgAF+A4IgIAAIgIAAIgJABIAAgEQAGgBACgCQACgCABgGIAAgyIgBgKIgCgHQgCgEgCgCQgDgCgEAAQgFAAgEADQgCABgCAEIgDAHIgBALIAAAxQAAAGACACQACACAGABIAAAEIgJgBIgIAAIgHAAIgJABIAAgEQAHgBACgCQACgCAAgHIAAg+IgBgJQgBgCgCgCIgHAAIAAgEIAMgCIAJgEIABAIIAAAKQAEgJAFgDQAFgEAHAAQAGAAAFADQAFAEADAGIADAJIABANIAAAwQAAAHACACQACACAHABIAAAEIgJgBgAA8A4IgFAAIgEAAIgGABIgXg2IgLAPIAAAXQgBAHADACQACACAHABIAAAEIgKgBIgIAAIgGAAIgKABIAAgEQAHgBADgCQACgCAAgHIAAhmQAAgIgCgCQgDgDgHAAIAAgDIAMgCIALgDIAABbIAagjIABgDIAAgCQAAgBAAgBQAAAAAAgBQAAAAAAAAQgBgBAAAAQgCgBgFAAIAAgFIAIABIAHAAIAIAAIAHgBIAAAFIgGABIgFADIgEAFIgPAVIAXAvIADAHIADAEIAHABIAAAEIgGgBgAipA4IgIAAIgHAAIgKABIAAgEQAHgBACgCQACgCAAgHIAAhAQAAgHgCgCQgCgDgHAAIAAgDIAMgCIAMgEIAABVQgBAHADACQACACAHABIAAAEIgKgBgAjOA4IgIAAIgIAAIgJABIAAgEQAGgBADgCQACgCgBgGIAAgyIgBgLIAAgGQgDgEgDgCQgDgCgEAAQgDAAgEADQgEABgCAEIgCAHIgBALIAAAxQgBAGADACQACACAGABIAAAEIgJgBIgIAAIgIAAIgJABIAAgEQAHgBACgCQACgCAAgHIAAhmQAAgIgCgCQgCgDgHAAIAAgDIAMgCIAMgDIAAA2QADgHAGgDQAEgEAHAAQAGAAAFAEQAFADADAGIADAJIABANIAAAwQAAAHACACQACACAHABIAAAEIgJgBgAm0A4IgIAAIgIAAIgJABIAAgEQAGgBACgCQACgCABgGIAAgyIgBgLIgCgGQgCgEgCgCQgDgCgFAAQgDAAgEADQgDABgDAEIgCAHIgBALIAAAxQAAAGACACQACACAGABIAAAEIgJgBIgIAAIgHAAIgKABIAAgEQAIgBACgCQABgCABgHIAAhmQgBgIgBgCQgCgDgIAAIAAgDIANgCIALgDIAAA2QAEgHAFgDQAEgEAHAAQAGAAAFAEQAFADAEAGIACAJQABAFAAAIIAAAwQAAAHACACQACACAHABIAAAEIgJgBgApzA4IgIAAIgIAAIgJABIAAgEQAGgBACgCQADgCgBgGIAAg0QAAgMgDgGQgDgEgGAAQgIAAgEAGQgEAGAAAMIAAAyQAAAGACACQACACAGABIAAAEIgJgBIgIAAIgGAAIgKABIAAgEQAGgBADgCQABgCABgGIAAg0IgBgKQAAgDgBgCIgFgGQgDgBgDAAQgEAAgEACQgDACgCAEIgCAHIgBALIAAAwQAAAGACACQADACAGABIAAAEIgKgBIgHAAIgJAAIgJABIAAgEQAIgBABgCQADgCAAgHIAAg+IAAgIIgCgDIgCgCIgHAAIAAgEIALgCIAJgEIABAJIAAAJQAFgJAFgDQAFgEAHAAQAHAAAFAEQAEADADAJQAEgJAFgDQAFgEAHAAQAHAAAFADQAFAEACAFQACAEABAFIAAALIAAAzQAAAHACACQADACAGABIAAAEIgJgBgAswA4IgHAAIgIAAIgKABIAAgEQAIgBABgCQACgCAAgGIAAgyIgBgLIgBgGQgCgEgCgCQgEgCgDAAQgEAAgFADQgCABgDAEIgDAHIAAALIAAAxQAAAGACACQABACAHABIAAAEIgKgBIgHAAIgIAAIgJABIAAgEQAHgBACgCQADgCAAgHIAAhmQAAgIgDgCQgCgDgHAAIAAgDIANgCIALgDIAAA2QAEgHAEgDQAFgEAGAAQAIAAAEAEQAFADADAGIADAJQABAFABAIIAAAwQgBAHACACQACACAHABIAAAEIgKgBgAuAA4IgJgBIgJABIgLABIAAgFQAGgBADgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgBgCIgCgFIgcg2IgGAJIAAAsIAAAIQABACADACIAHACIAAAFIgJgBIgJgBIgFAAIgGABIgIABIAAgFIAIgCQAEgCAAgCQABgCgBgGIAAhkQABgFgBgDQAAgDgEgBIgIgCIAAgFIALACIAIAAIAJAAIAKgCIAAAFIgIACQgDABgBADIAAAIIAAAvIAkg0IABgCIAAgCQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAAAIgJgCIAAgFIAKABIAHAAIAHAAIAJgBIAAAFIgIACQgDAAgDADQgCACgDAEIgbAnIAjBBIAFAHQACADAEABQADACADAAIAAAFIgLgBgAmRg4IAQgeIASAAIgaAegAsMg4IAQgeIARAAIgZAegAEmg5IgRgRIgRARIgIAAIAVgdIAIAAIAUAdgAB2g5IgRgRIgSARIgHAAIAUgdIAHAAIANARIANgbIASAAIgaAfIgDAAIAHAIgAhqg5IgRgRIgRARIgIAAIAVgdIAHAAIANARIANgbIARAAIgZAfIgDAAIAGAIgAi3g9QgCgDgBgFQABgFACgEQACgCAEAAQAEAAACACQACAEAAAFQAAAFgCADQgCADgEAAQgEAAgCgDg");
	this.shape.setTransform(99.2,-4.325);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1.4,-14,195.7,19.4);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.tagline();
	this.instance.setTransform(216,41,0.32,0.32);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_2
	this.instance_1 = new lib.light();
	this.instance_1.setTransform(-4,0,0.7,0.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,0,679,175);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AC0A+QgCgCAAgDQAAgBAAAAQAAgBABgBQAAAAAAgBQABAAAAgBQAAAAABgBQABAAAAAAQABgBAAAAQABAAAAAAQADAAADACQAAABAAAAQABABAAAAQAAABAAABQABAAAAABQAAADgCACQgDACgDAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBgBAAAAgAhWA+QgCgCAAgDQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAABgBQACgCADAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQAAABAAAAQABABAAAAQAAABAAABQAAAAAAABQAAADgBACQgCACgEAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBgBAAAAgALdAjQgEgFgBgJIAHAAQABAHAEADQADAFAJAAQAGAAAEgDQAFgDAAgGQAAgFgFgEIgLgGQgLgEgDgDQgHgEAAgJQAAgIAHgGQAGgEAIAAQANAAAFAIQAEAEAAAIIgIAAQAAgGgDgDQgEgEgHAAQgFAAgDADQgEADAAAFQAAAEAEADIAMAGIALAFIAEAEQAFAFAAAHQAAAKgIAGQgGAEgKAAQgMAAgGgIgAHzAjQgJgLABgRQAAgTAKgKQAHgHALAAQAKAAAHAFQAGAGABAKIgHAAQgEgOgNAAQgIAAgGAIQgGAIAAANQAAAPAHAIQAFAGAIAAQAIAAAFgEQAEgFABgJIAHAAQgBAJgDAGQgGAKgOAAQgNAAgIgIgABmAkQgFgEgBgHIAAgMIAAgpIAIAAIAAApIAAALIACAFQACAEAFACQADABAGAAQAFAAAFgCQAFgEABgIIABgJIAAgpIAIAAIAAApIgBAMIgBAFQgDAHgGADQgGADgIAAQgNAAgHgHgAjjAjQgJgKAAgSQAAgSAJgKIAJgGQAFgCAGAAQALAAAFAFQAHAGABAKIgIAAQgBgGgDgEQgEgEgIAAQgIAAgGAGQgGAJgBAOQABAQAHAIQAGAFAJAAQAIAAAIgEIAAgSIgOAAIAAgHIAVAAIAAAdQgKAHgNAAQgOAAgIgIgAmEAmQgHgFABgJQgBgIAHgHIAIgHIgHgIIgBgHQAAgGAEgEQAFgEAHAAQAFAAAEADQAFAEAAAGQAAAFgDAFQgDAEgGAEIAPAUQADgFgBgJIAHAAIAAACIgBAKQgBAEgDAEIAJAMIgJAAIgEgGIgHAFQgEACgHAAQgJAAgGgFgAl+AOQgFAEAAAGQAAAFAEAEQAEAEAHAAQAIAAAEgHIgPgWIgHAGgAl7gTQgCACAAADIABAFIAGAJIAHgHQACgDAAgEQAAgDgCgCQgDgCgDAAQgEAAgCACgAPiAqIAAgGIAkg5IgiAAIAAgHIArAAIAAAGIgkA5IAkAAIAAAHgAPNAqIgig6IAAA6IgIAAIAAhGIAJAAIAiA6IAAg6IAIAAIAABGgANuAqIAAhGIAmAAIAAAHIgeAAIAAAXIAcAAIAAAHIgcAAIAAAaIAfAAIAAAHgAMzAqIAAhGIANAAQANAAAFACQAFACADAFQADAEgBAFQABALgMADQAPAEAAAOQAAAKgGAFQgEADgEABIgSABgAM7AjIAHAAIAKAAIAGgBQADgCABgDQACgDAAgEQgBgEgCgEQgCgDgDgBIgOgBIgHAAgAM7ACIAGAAQAKAAAEgCQAGgCgBgHQAAgEgBgDQgCgDgDgBIgNgBIgGAAgAKmAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAJjAqIAAhGIAMAAIAOABQANACAHAKQAHAJAAANQAAAOgIAKQgIAJgMACIgOAAgAJrAjIAGAAIAMAAIAHgDQAGgEADgGQACgHAAgIQABgMgHgIQgFgGgJgBIgMgBIgEAAgAIuAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAHaAqIgSgeIgMAAIAAAeIgIAAIAAhGIAMAAIANABIAHACQAGACADAFQACAFABAFQAAANgPAGIASAfgAG8AFIAEAAIAKAAIAFgBQAIgDAAgJQAAgIgHgDIgFgCIgLAAIgEAAgAF+AqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAFkAqIAAg+IgUA+IgIAAIgVg+IAAA+IgHAAIAAhGIALAAIAUA9IAVg9IAMAAIAABGgADrAqIAAg/IgSAAIAAgHIAtAAIAAAHIgTAAIAAA/gADMAqIgGgTIgbAAIgGATIgIAAIAYhGIAHAAIAYBGgACuARIAWAAIgMgjgABHAqIAAgiIghAAIAAAiIgIAAIAAhGIAIAAIAAAeIAhAAIAAgeIAIAAIAABGgAgHAqIAAg/IgTAAIAAgHIAsAAIAAAHIgSAAIAAA/gAhjAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAh9AqIAAgiIghAAIAAAiIgIAAIAAhGIAIAAIAAAeIAhAAIAAgeIAIAAIAABGgAkDAqIgig6IAAA6IgIAAIAAhGIAJAAIAiA6IAAg6IAIAAIAABGgAnWAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAnqAqIgSgdIgSAdIgJAAIAWglIgVghIAJAAIARAcIARgcIAJAAIgWAhIAXAlgApEAqIAAg+IgVA+IgIAAIgVg+IAAA+IgHAAIAAhGIAMAAIAUA9IAUg9IAMAAIAABGgAqQAqIgGgTIgbAAIgHATIgIAAIAZhGIAHAAIAYBGgAqvARIAXAAIgMgjgArsAqIAAhGIAJAAIAAA/IAeAAIAAAHgAshAqIgig6IAAA6IgHAAIAAhGIAJAAIAiA6IAAg6IAHAAIAABGgAuAAqIAAhGIAnAAIAAAHIgfAAIAAAXIAdAAIAAAHIgdAAIAAAaIAgAAIAAAHgAuaAqIAAhGIAIAAIAABGgAuvAqIgSgeIgNAAIAAAeIgIAAIAAhGIANAAIAMABIAIACQAFACAEAFQACAFAAAFQAAANgOAGIASAfgAvOAFIAFAAIAKAAIAEgBQAJgDgBgJQAAgIgGgDIgFgCIgLAAIgFAAgAv8AqIAAg/IgTAAIAAgHIAtAAIAAAHIgSAAIAAA/gAMNASIAAgFIAdAAIAAAFgADDgjIgLgJIgKAJIgHAAIAOgOIAIAAIAOAOgAhEgjIgLgJIgLAJIgHAAIANgOIAJAAIAOAOgAtigjIgKgJIgKAJIgIAAIAOgOIAJAAIAGAHIAAgFIABAAQAIAAAAgFQAAgBAAAAQAAgBAAgBQgBAAAAAAQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgGACIAAgFQAFgCAEAAQAEAAADADQADACAAAFQAAAFgDACQgDACgGAAIAAAFIgBAAIAEAEgAqfglIgGgCIgGgDQgEAAgBAGIgFgBIACgGQADgFAFAAQADAAAFADIAFACIACABQAEAAACgGIAEABIgCAGIgDAEQgBAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgDgBg");
	this.shape.setTransform(103.5,7.875);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.4,1.5,207.9,12.8);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkFA7QgHgFAAgJQAAgIAGgFIAJgFQgIgCAAgGQAAgEAFgDIAIgEQgOgGAAgOQAAgMAIgGQAHgGALAAIALABIAVAAIAAAIIgOgBQAGAHAAAKQAAALgHAEQgEADgMADIgLADQgEACAAACQAAABAAABQAAAAABABQAAAAAAAAQABABABAAIALACIAPABQARAEAAAPQAAAMgKAFQgIAFgOABQgQAAgJgHgAj8AjQgHADAAAGQAAAGAGADQAHAEAKAAQAMAAAGgFQAEgDAAgFQAAgMgXAAQgJAAgGADgAj4gXQgEAEAAAHQAAAHAEADQAEADAHAAQAHAAAEgCQAEgEAAgHQAAgGgEgEQgEgGgHAAQgGAAgFAFgAhXBBIAAgKQAKABAFgEQADgDADgIIACgGIgYhGIALAAIATA6IAUg6IALAAIgXBBIgIAUQgIAPgSAAIgDAAgAHRA7QgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgBQACgCADAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABQACABAAADQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBABQgCACgDAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAHEAhQgGgFgCgJIgBgMIAAgqIALAAIAAAqQAAALACAEQAEAFAIAAQAKAAAFgIQADgEAAgLIAAgnIAKAAIAAAFIABAAIADgFIACgDIgBAAIgCgCQgDgDABgDQABgDACgBQADgCACABQADABACADQABACgBAFQgCAIgMAJIAAAlIAAAHIAAAEIACAKIgKAAIgBgEIgBgGQgCAFgDADQgGAEgIAAQgJAAgGgEgAF1AdQgKgLAAgSQAAgSAKgLQAHgIALAAQAJAAAFAEQADACADAGIAAgoIALAAIAABPQAAARABAEIgKAAIgBgIIAAgCQgDAFgDADQgGAEgIAAQgMAAgHgIgAF9gWQgHAJAAANQAAAOAGAIQAFAGAIgBQAIABAEgGQAHgIAAgOQAAgNgGgJQgFgGgIAAQgIAAgEAGgACTAgQgHgFAAgLQAAgPAQgFQAJgEASgDIAAgCQAAgIgCgCQgEgFgIAAQgOAAgCALIgLAAQABgIAGgFQAHgHANAAQALAAAHAFQAFAEABAJIAAAJIAAAaQAAANACAGIgKAAQgBgEAAgGQgHAMgOAAQgKAAgGgFgAChADQgKAEAAAIQAAAGAEADQADAEAGAAQALAAAFgJQADgFAAgKIAAgGQgQACgGADgAmVAgQgIgFAAgLQAAgPARgFQAJgEARgDIAAgCQAAgIgCgCQgEgFgIAAQgOAAgCALIgKAAQABgIAFgFQAHgHANAAQAMAAAGAFQAFAEABAJIABAJIAAAaQAAANACAGIgKAAQgCgEAAgGQgGAMgPAAQgJAAgGgFgAmIADQgKAEAAAIQAAAGAEADQAEAEAGAAQALAAAEgJQADgFAAgKIAAgGQgPACgHADgAAbAeQgCgDAAgDIAAgzIgKAAIAAgIIAKAAIAAgVIALAAIAAAVIARAAIAAAIIgRAAIAAAjIAAANQABAHAGgBQAGAAAFgCIAAAJQgGACgHAAQgKABgEgHgAEqAjIAAgrIAAgJQgCgKgMgBQgJABgFAHQgDAFAAAJIAAApIgKAAIAAgpQAAgMgCgDQgDgGgJgBQgFAAgDACQgEACgCAEQgDAFAAAKIAAAoIgLAAIAAgwIAAgPIgBgHIAKAAQABAEAAAFQAHgLAOAAQAOAAAFAMQAIgMAOAAQAOAAAFAJQACAEAAAHIAAAJIAAArgABwAjIAAgnQAAgNgDgDQgDgIgJAAQgKAAgFAJQgDAGAAAKIAAAmIgLAAIAAhkIALAAIAAAmQAHgKANAAQAIAAAGADQAGAFACAIIABAQIAAAogAhvAjIgeglIAeghIANAAIgeAgIAgAmgAiYAjIAAhkIALAAIAAA/IAAAlgAkmAjIAAgnQAAgNgCgDQgDgIgJAAQgKAAgGAIQgDAGAAALIAAAmIgKAAIAAguIgBgSIgBgGIAKAAQABAEAAAGQAIgMAOAAQAKAAAGAFQAFAFABAIIABAOIAAAogAn1AjIAAgvIgJAAIAAgIIAJAAIAAgsIAQAAIAUABQASADAKAOQAJAOAAASQAAAUgKANQgLANgRACIgVABgAnqAZIAIAAIAPgBQAGgBAGgDQAFgDAEgFQAHgMAAgOQAAgSgJgLQgHgJgMgCIgSAAIgFAAIAAAiIAYAAIAAAIIgYAAgAmGgtIgGgDIgEgFIgCgGIAGAAQACAFADABQADACAEABQAEgBADgCQAEgCAAgEIAGAAQAAADgBADIgFAFIgFADIgGABIgGgBgAg/guIANgRIAKAAIgQARg");
	this.shape.setTransform(39.62,10.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A7EBE").s().p("Ap9B/IAAj9IT7AAIAAD9g");
	this.shape_1.setTransform(39.85,10.675);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.9,-2,127.6,25.4);


(lib.Symbol10copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABLBjQAjgjATgjQgKAEgJAAQgUAAgNgPQgQgRAAgcQAAgbAOgRQAPgTAYAAQAWAAAPAQQAQASAAAdQAAAVgJAUQgJAUgVAYQgVAZgSAQgABchFQgHAOAAAaQAAAZAHAOQAHAOAPAAQAfAAAAgyQAAg4gfAAQgOAAgIANgALjBNQgNgNgCgaIAKAAQABAMADAIQAJATAYAAQASAAALgMQAJgLAAgRQAAgbgUgIQgJgDgQAAIgDAAIAAgJIADAAQAQAAAJgHQANgJAAgTQAAgOgHgIQgIgJgOAAQgTAAgKAOQgEAHgDAMIgIAAQAFgvAsAAQAXAAANAOQALALAAASQAAAPgJAKQgIAKgQAFQAOADAJAGQARAMAAAYQAAAWgQAPQgQAPgYAAQgYAAgNgNgAG4BCQgPgaAAgoQAAgUAFgRQAEgSAHgMQAOgXAbAAQARAAANALQAOALAHAZQAFAUAAAXQAAAlgNAaQgNAbgeAAQgcAAgOgYgAHMhEQgMAUAAAwQAAA0APATQAIALALAAQAhAAAAhSQAAgngIgVQgEgLgHgFQgGgGgIAAQgNAAgJAOgADVBWQgFgFAAgGQAAgHAFgEQAEgFAGAAQAHAAAEAFQAFAEAAAHQAAAGgFAFQgEAEgHAAQgGAAgEgEgAhMBCQgPgaAAgoQAAgUAFgRQAEgSAHgMQAOgXAbAAQARAAANALQANALAHAZQAFAUAAAXQAAAlgNAaQgMAbgeAAQgcAAgOgYgAg4hEQgMAUAAAwQAAA0APATQAIALALAAQAhAAAAhSQAAgngIgVQgEgLgHgFQgGgGgIAAQgNAAgJAOgAiaBWQgFgFAAgGQAAgHAFgEQAEgFAGAAQAHAAAEAFQAFAEAAAHQAAAGgFAFQgEAEgHAAQgGAAgEgEgAklBKQgQgSAAgcQAAgcAUgeQAKgPARgTQASgSATgQIAOAAQgmAjgTAiQAKgEAJAAQAVAAAOAPQAQARAAAcQAAAbgPASQgQASgYAAQgYAAgQgQgAkWgJQgIANAAAXQAAA3AgAAQAQAAAIgNQAIgOAAgaQAAgZgIgNQgHgPgQAAQgRAAgIAPgAqeBNQgNgNgBgaIAJAAQABAMAEAIQAIATAYAAQASAAALgMQAKgLAAgRQAAgbgUgIQgKgDgPAAIgDAAIAAgJIADAAQAQAAAJgHQANgJAAgTQAAgOgIgIQgHgJgPAAQgTAAgJAOQgFAHgCAMIgIAAQAEgvAtAAQAXAAAMAOQALALAAASQAAAPgIAKQgJAKgQAFQAPADAIAGQASAMAAAYQAAAWgQAPQgQAPgZAAQgXAAgOgNgAJBBYIAAgPQAfgjARgYQARgXAHgNQAHgOAAgKQAAgMgIgIQgIgJgNAAQgKAAgIAFQgIAEgEAHQgFAIgCAOIgJAAQACgYAIgLQAHgIAKgFQALgFANAAQATAAANAKQAHAGAEAIQAEAIAAAJQAAANgHANQgHAOgUAXIgvA3IBTAAIgDATgAEXBYIAAgPQAfgjARgYQARgXAHgNQAHgOAAgKQAAgMgIgIQgIgJgNAAQgKAAgIAFQgIAEgEAHQgFAIgCAOIgJAAQACgYAIgLQAHgIAKgFQALgFANAAQATAAANAKQAHAGAEAIQAEAIAAAJQAAANgHANQgHAOgUAXIgvA3IBTAAIgDATgAnIBYIAAgPQAfgjARgYQARgXAHgNQAHgOAAgKQAAgMgIgIQgIgJgNAAQgKAAgIAFQgIAEgEAHQgFAIgCAOIgJAAQACgYAIgLQAHgIAKgFQALgFANAAQATAAANAKQAHAGAEAIQAEAIAAAJQAAANgHANQgHAOgUAXIgvA3IBTAAIgDATgAs/BYIAAgPQAegjARgYQASgXAHgNQAGgOAAgKQAAgMgHgIQgJgJgNAAQgJAAgIAFQgIAEgFAHQgFAIgCAOIgJAAQADgYAIgLQAGgIALgFQALgFAMAAQAUAAAMAKQAHAGAFAIQAEAIAAAJQAAANgIANQgHAOgUAXIguA3IBSAAIgCATgAomAVIAAgMIBFAAIAAAMg");
	this.shape.setTransform(105.975,-61.075);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(22.8,-71,166.39999999999998,19.9);


(lib.Symbol8copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMIBpIAAgMQANgBAHgEQAHgFAEgLIAIgSIgkhdQgCgHgDgCQgEgCgJAAIAAgFIAZABIAYgBIAAAFIgKABQAAABgBAAQAAAAgBABQAAAAAAABQAAAAAAABIABAGIAaBFIAahEIACgHQAAgCgDgCIgLgBIAAgFIASABIAVgBIAAAFQgJAAgDADQgEADgDAFIgtB1QgFAOgJAGQgIAHgNAAIgDAAgArNBlQgEgEAAgGQAAgGAEgEQAEgEAGAAQAFAAAEAEQAEAEAAAGQAAAGgEAEQgEAEgGAAQgFAAgEgEgAIXAxQgPgLgIgXQgFgQAAgUQAAgkARgYQAIgLAOgHQALgFAOAAQAWAAAQAOIAIgNIAEAAIAAAuIgFAAQgKgnggAAQgYAAgLAVQgLAVAAAgQAAAfAKATQALAXAYgBQATAAALgMQAKgMACgWIAIAAQgBATgGAMQgHANgNAHQgLAGgPAAQgTAAgQgMgAC2A8IAAiLIgBgJQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAgBQgEgBgJAAIAAgEQATgCARgEIAABBQAFgHAEgEQAIgHANgBQAUABAMAQQAMARAAAZQAAAZgNAQQgMARgUAAQgWAAgJgUIgLAUgADJACQAAAzAbAAQANAAAHgNQAHgOAAgZQAAgzgaABQgcgBAAA0gABPArQgMgQAAgZQAAgaANgQQANgRAVAAQAWAAAMARQAMARAAAZQAAAYgMARQgNARgWAAQgVAAgNgRgABegmQgHAOAAAaQAAA1AaAAQANAAAHgOQAHgNAAgaQAAg1gaAAQgNAAgHANgAhpAxQgQgLgIgXQgFgQAAgVQAAgkARgXQASgXAeABQAVAAARANIAKgOIAEAAIAAAvIgGAAQgEgNgEgIQgGgIgJgGQgJgEgLAAQgSAAgLALQgSASAAAtQAABMAuAAQAQAAARgKIAAgoQAAgEgCgCQgBgCgDAAQgEgCgJgBIAAgGIAbABIAbgBIAAAGQgLABgDACQgCACAAAGIAAAnQgdASgZgBQgUAAgQgLgAkXAsQgNgQAAgbQAAgZANgRQANgQAVAAQAOAAAKAIQAKAHAFANQAEAMAAAQIhHAAQABAXADAKQAIAUAUAAQAMAAAIgIQAIgIACgPIAKAAQgCAOgHAJQgMARgWgBQgXABgMgRgAkQgJIAzAAQgCgpgXAAQgXAAgDApgALPA0QgEgEgBgHQgCgHABgNIABhDIgQAAIAAgHQAWgBAHgiIAGAAIAAAhIAcAAIAAAJIgcAAIAABFQAAAOACAGQADAHAJAAQAGAAAKgEIAAAHQgNAHgLAAQgNAAgHgIgAEpA0QgKgJAAgNQAAgXAbgKQAQgGAUgDIAAgOQAAgMgEgFQgFgHgLAAQgJAAgFAEQgGAEAAAGIAAACIAAAEQAAAKgKAAQgHAAAAgIQAAgLAKgIQAMgKARAAQAKABAIADQAIAEAFAGQAGAIAAASIAAAwQAAAMACAFQACAFAFgBIAHgBIAAAHIgOABQgJAAgEgEQgEgFgBgLQgFAJgFAEQgIAIgPAAQgOAAgJgIgAFDACQgRAIAAASQAAAKAGAGQAFAFAJAAQANABAFgJQAGgIAAgTIAAgTQgRADgKAEgArnA0QgJgJAAgNQAAgXAbgKQAPgGAUgDIAAgOQAAgMgDgFQgFgHgLAAQgJAAgGAEQgFAEAAAGIAAACIAAAEQAAAKgKAAQgIAAAAgIQAAgLALgIQAMgKAQAAQAKABAJADQAIAEAFAGQAGAIAAASIAAAwQAAAMACAFQACAFAFgBIAGgBIAAAHIgNABQgJAAgEgEQgFgFgBgLQgFAJgEAEQgJAIgOAAQgPAAgJgIgArNACQgQAIAAASQAAAKAFAGQAGAFAJAAQAMABAGgJQAFgIAAgTIAAgTQgQADgLAEgAKZA6IgbABIAAgFQALAAADgDQAEgDAAgHIAAhLIgBgIQgBgEgDgBQgDgBgJAAIAAgEQATgCARgEIAABjIABAIQABACADABQAEACAIAAIAAAFIgbgBgAGgA6IgbABIAAgFQALAAADgDQAEgDAAgHIAAh4IgBgJQgBgDgDgBQgDgBgJAAIAAgEQASgCASgEIAACQIABAIQABACADABQAEACAIAAIAAAFIgbgBgAAgA6IgbABIAAgFQALAAADgDQAEgDAAgHIAAh4IgBgJQgBgDgDgBQgDgBgJAAIAAgEQASgCASgEIAACQIABAIQABACADABQAEACAIAAIAAAFIgbgBgAlGA6IgaABIAAgFQAJAAADgDQAEgDAAgHIAAg5QAAgPgEgGQgFgIgNgBQgMAAgIAKQgFAGAAAPIAAA4IABAIQABACADABQAEACAHAAIAAAFIgagBIgaABIAAgFQALAAADgDQADgDAAgHIAAh4IgBgJQgBgDgDgBQgDgBgJAAIAAgEQATgCARgEIAAA/QAMgQATgBQATABAKAPQAGAIAAASIAAA4IABAIQABACADABQAEACAIAAIAAAFIgagBgAnhA5IgeACIAAgGQAKgBAEgCQAEgBABgCIABgKIAAiDIgNAAQgPAAgGAKQgEAFgEAOIgGAAIAGgkIBpAAIAHAkIgGAAQgFgRgFgFQgGgHgMAAIgQAAIAACDQAAAHACADQABACADABQAEACAKABIAAAGIgegCgApvA6IgbABIAAgFQALAAADgDQAEgDAAgHIAAhLIgBgIQgBgEgDgBQgDgBgJAAIAAgEQATgCARgEIAABjIABAIQABACADABQAEACAIAAIAAAFIgbgBgAsyA5IgeACIAAgGQAKgBAEgCQADgBACgCIABgKIAAiDIgNAAQgPAAgHAKQgEAFgEAOIgGAAIAHgkIBpAAIAGAkIgFAAQgFgRgGgFQgGgHgMAAIgPAAIAACDQAAAHABADQABACAEABQAEACAKABIAAAGIgegCgAKPhOQgEgEAAgGQAAgFAEgEQAEgFAFAAQAGAAADAFQAEAEAAAFQAAAGgEAEQgDADgGAAQgFAAgEgDgAp5hOQgEgEAAgGQAAgFAEgEQAEgFAFAAQAGAAADAFQAEAEAAAFQAAAGgEAEQgDADgGAAQgFAAgEgDg");
	this.shape.setTransform(80.075,50.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.7,40.4,175.6,21);


(lib.Symbol4copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Rectangl();
	this.instance.setTransform(-114,-36,0.7,0.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-114,-36,210,80.5);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol24("synched",0);
	this.instance.setTransform(103.45,10.6,1.5,1.5,0,0,0,103.5,10.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.95,scaleY:0.95,x:103.5,alpha:1},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(831).to({startPosition:0},0).to({_off:true},1).wait(2196));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.5,-1.4,295.1,30);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol19("synched",0);
	this.instance.setTransform(98.8,13.8,1.5,1.5,0,0,0,98.8,9.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.95,scaleY:0.95,y:9.15,alpha:1},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:9.8},10,cjs.Ease.get(1)).wait(73).to({startPosition:0},0).to({_off:true},1).wait(4).to({_off:false},0).wait(131).to({startPosition:0},0).to({_off:true},1).wait(2120));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-47.3,-21.9,293.5,29.099999999999998);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol16("synched",0);
	this.instance.setTransform(334.65,86.25,0.4,0.4,0,0,0,334.7,86.3);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:334.6,scaleX:1.1,scaleY:1.1,x:334.6,y:86.35,alpha:1},8,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:86.3},7,cjs.Ease.get(1)).wait(267).to({startPosition:0},0).to({_off:true},1).wait(257));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.8,-8.6,746.9,192.5);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol15("synched",0);
	this.instance.setTransform(103.8,-18,1,1,0,0,0,103.8,7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:9,alpha:1},8,cjs.Ease.get(1)).to({y:7},5,cjs.Ease.get(1)).wait(276).to({startPosition:0},0).to({_off:true},1).wait(150));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.4,-23.5,207.9,39.8);


(lib.Symbol11copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.setTransform(43.4,7.6,1,1,0,0,0,43.4,7.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.9,scaleY:0.9},9,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.9,-2,127.6,25.4);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.setTransform(43.4,7.6,1,1,0,0,0,43.4,7.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14,cjs.Ease.get(1)).wait(12).to({startPosition:0},0).to({_off:true},1).wait(1938));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.9,-2,127.6,25.4);


(lib.Symbol5copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_6
	this.instance = new lib.Symbol10copy("synched",0);
	this.instance.setTransform(71.4,186.45,1,1,0,0,0,120.6,10.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:156.4,alpha:1},8,cjs.Ease.quadOut).wait(262).to({startPosition:0},0).to({_off:true},1).wait(4023));

	// Layer_2
	this.instance_1 = new lib.Symbol4copy("synched",0);
	this.instance_1.setTransform(150.5,144.15,1,1,0,0,0,0,5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(6).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(258).to({startPosition:0},0).to({_off:true},1).wait(4023));

	// Layer_4
	this.instance_2 = new lib.Symbol8copy("synched",0);
	this.instance_2.setTransform(211,116.9,1,1,0,0,0,66.5,13.3);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:128,alpha:1},8,cjs.Ease.quadOut).wait(262).to({startPosition:0},0).to({_off:true},1).wait(4023));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.4,103.2,338.79999999999995,80.49999999999999);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4
	this.instance = new lib.Symbol23("synched",0);
	this.instance.setTransform(83.55,18.15,1.05,1.05,0,0,0,103.4,10.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(119).to({_off:false},0).wait(51).to({startPosition:51},0).to({_off:true},1).wait(800));

	// Layer_2
	this.instance_1 = new lib.Symbol22("synched",0);
	this.instance_1.setTransform(90.6,40.65,2,2,0,0,0,107.5,49.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(99).to({_off:false},0).to({regY:49,scaleX:1,scaleY:1,x:90.5,y:60,alpha:1},18,cjs.Ease.get(1)).wait(53).to({startPosition:0},0).to({_off:true},1).wait(800));

	// Layer_11
	this.instance_2 = new lib.Symbol18("synched",0);
	this.instance_2.setTransform(81.8,32.8,1,1,0,0,0,98.8,9.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).wait(80).to({startPosition:80},0).to({alpha:0,startPosition:98},14,cjs.Ease.get(1)).wait(57).to({startPosition:155},0).to({_off:true},1).wait(800));

	// Layer_1
	this.instance_3 = new lib.Symbol21("synched",0);
	this.instance_3.setTransform(83.05,73.5,2,2,0,0,0,83,86.5);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({scaleX:1,scaleY:1,x:83,y:86.5,alpha:1},17,cjs.Ease.get(1)).wait(82).to({startPosition:0},0).to({alpha:0},14,cjs.Ease.get(1)).wait(57).to({startPosition:0},0).to({_off:true},1).wait(75).to({_off:false},0).wait(725));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-208.3,-97.5,579,356);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_289 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(289).call(this.frame_289).wait(1));

	// cta copy
	this.instance = new lib.Symbol11copy();
	this.instance.setTransform(152.75,212.6,0.73,0.73,0,0,0,43.6,7.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(68).to({_off:false},0).wait(222));

	// cta
	this.instance_1 = new lib.Symbol11("synched",0);
	this.instance_1.setTransform(152.75,212.6,0.73,0.73,0,0,0,43.5,7.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41).to({_off:false},0).to({_off:true},27).wait(222));

	// Layer_7
	this.instance_2 = new lib.Symbol20("synched",0);
	this.instance_2.setTransform(151,149.5,1,1,0,0,0,83,86.5);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(119).to({_off:false},0).wait(171));

	// logo
	this.instance_3 = new lib.Logo();
	this.instance_3.setTransform(233,214,0.32,0.32);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(290));

	// Layer_9
	this.instance_4 = new lib.Symbol14("synched",0);
	this.instance_4.setTransform(156.2,120.1,1.02,1.02,0,0,0,334.5,86.4);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(7).to({_off:false},0).wait(112).to({startPosition:112},0).to({regX:334.4,regY:86.5,scaleX:0.65,scaleY:0.65,x:151.65,y:55,startPosition:129},17,cjs.Ease.get(1)).wait(154));

	// Layer_8 copy
	this.instance_5 = new lib.Symbol17("synched",0);
	this.instance_5.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(119).to({_off:false},0).to({alpha:1},11,cjs.Ease.get(1)).wait(160));

	// Layer_6
	this.instance_6 = new lib.Symbol13("synched",0);
	this.instance_6.setTransform(152.2,51.75,1.11,1.11,0,0,0,103.8,7);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(290));

	// Layer_5
	this.instance_7 = new lib.Symbol5copy("synched",0);
	this.instance_7.setTransform(103.8,126.4,0.6,0.6,0,0,0,63,64);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(19).to({_off:false},0).wait(271));

	// Layer_8
	this.instance_8 = new lib.Symbol17("synched",0);
	this.instance_8.setTransform(150,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(290));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-223.5,-34.5,761.7,356);


// stage content:
(lib._300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,150,126.5);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1694524452485", id:"bg"},
		{src:"images/h2.png?1694524452485", id:"h2"},
		{src:"images/h3.png?1694524452485", id:"h3"},
		{src:"images/light.png?1694524452485", id:"light"},
		{src:"images/Logo.png?1694524452485", id:"Logo"},
		{src:"images/Rectangl.png?1694524452485", id:"Rectangl"},
		{src:"images/tagline.png?1694524452485", id:"tagline"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;