(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,480);


(lib.h2 = function() {
	this.initialize(img.h2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,594,426);


(lib.h3 = function() {
	this.initialize(img.h3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,396);


(lib.light = function() {
	this.initialize(img.light);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,250);


(lib.Logo = function() {
	this.initialize(img.Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,154,117);


(lib.Rectangl = function() {
	this.initialize(img.Rectangl);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,115);


(lib.tagline = function() {
	this.initialize(img.tagline);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,750,185);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3E8DCA").s().p("AMGB0QgDgFgBgFQABgGADgDQADgFAEAAQAEAAADAFQADADABAGQgBAFgDAFQgDADgEAAQgEAAgDgDgAnhB0QgCgFgBgFQABgGACgDQADgFAFAAQAEAAADAFQADADAAAGQAAAFgDAFQgDADgEAAQgFAAgDgDgArSB0QgJgFgFgHQgEgGABgKQgBgKADgGQAFgFAJgEIgHgHQgDgDAAgEQAAgHAGgFQAEgFAKgCQgKgFgFgHQgFgJgBgLQABgSAHgIQAKgJAOAAIAKABIAJAEIAZAAIAAAKIgSgBQADAFAAAFQACAEgBAGQAAAIgCAHQgEAHgFAFIgFADIgFADIgJADIgMAEQgFACAAADQgBAAAAAAQgBABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQAAABABAAQABACAEABIAKABIANABIAJABIAGADQAIAFACAFQAFAIgBAHQABALgGAIQgFAJgIAEQgKAEgLAAQgMAAgIgDgArWBLQgGAEgBALQAAAGAFAEQADAGAHADQAGADAKAAQAMAAAJgGQAHgGAAgKQAAgLgIgEQgJgGgNABQgOgBgIAGgArKgYQgFAIAAAOQAAAMAEAJQAEAGAJAAQAIAAADgGQAGgJAAgNQAAgOgGgHQgDgIgIAAQgJAAgDAIgASPBMIgJgBQgDgBgDgDIgJgIQgHAGgFAEQgIADgKAAQgPAAgKgKQgMgKgFgSQgGgRgBgZQABgYAGgRQAFgTAMgJQAKgKAPAAQAQAAAKAKQALAJAFATQAHASgBAZQAAAMgCAMQgCANgEALQAGANAEAGQAFAFAFAAIAAAGgARCg5QgJASAAAjQAAAiAJAVQAIASAPABQAQgBAIgSQAJgTAAgiQAAgkgJgTQgIgVgQAAQgPAAgIAVgAJvBFQgHgIgEgMQgEgNgBgQQABgSAEgLQAEgNAHgHQAIgIAJABQAIgBAEAEQAGAEAEALIAAgfIgVAAIAAgHIAVAAIAAgEQAAgIgDgDQgBgBgJAAIAAgGIAPgBIANgEIAAAbIAMAAIAAAHIgMAAIAABlIAAAKQABADAEABIAHAAIAAAFIgIABIgHABIgIACIgBgJIgBgKQgEALgFAFQgHAEgHAAQgKAAgIgHgAJuATQABAZAFAMQAFANAKABQAKgBAFgMQAEgNABgXQgBgZgEgNQgFgNgLAAQgTAAgBAxgAhABFQgJgIgFgMQgEgNAAgRQAAgRAEgMQAFgNAJgIQAHgGALAAQAGgBAEACQAEADAFAFIAEgMIAEAAIAAAnIgFAAIgBgKIgDgHQgCgHgFgDQgFgEgEAAQgLAAgGAOQgFAOAAAXQAAAZAFALQAFANALAAQAQAAAFgfIAGAAQgBATgIAKQgHAKgMAAQgLAAgHgHgAjgBFQgIgIgFgMQgEgNAAgRQAAgRAEgMQAFgNAIgIQAJgGAKAAQAGgBAEACQAEADAEAFIAFgMIADAAIAAAnIgDAAIgDgKIgDgHQgCgHgFgDQgEgEgFAAQgKAAgGAOQgFAOAAAXQAAAZAFALQAFANALAAQARAAADgfIAHAAQgCATgHAKQgIAKgMAAQgLAAgHgHgAL0A9QgKgRAAgZQAAgSAFgMQAEgMAJgIQAHgGALAAQAQAAAHAOQAJANABAbIg2AAIABATQABAHACAFQADAKAEAFQAGAFAHAAQAKAAAFgHQAHgIACgQIAGAAQgBASgKALQgHAKgOAAQgRAAgKgPgAMgAIQgBgTgEgLQgEgKgKAAQgIABgFAJQgGALAAATIAmAAIAAAAgAHtA9QgJgRAAgZQgBgSAFgMQAEgMAJgIQAHgGALAAQAPAAAJAOQAIANABAbIg2AAIAAATIAEAMQACAKAFAFQAGAFAHAAQAJAAAHgHQAFgIACgQIAHAAQgBASgJALQgJAKgNAAQgRAAgKgPgAIaAIQgBgTgFgLQgEgKgJAAQgJABgFAJQgFALgCATIAoAAIAAAAgAFCBCIgBgMQgFAMgFAFQgGAFgIgBQgHAAgHgDQgFgDgEgGQgCgFgBgFIgBgQIAAg0QAAgIgCgDQgDgDgJAAIAAgFIAPgBIANgDIAABLQAAAQAFAFQADAHAIAAQALAAAEgIQAEgHAAgQIAAgxQABgIgEgDQgCgDgHAAIAAgFQAHABAHgCIANgDIAABcIABAIQAAAAABABQAAABAAAAQABABAAAAQABAAABAAIAIABIAAAEQgIAAgFACQgGACgGACIAAgKgAC7BCQgHgGAAgOQAAgMADgHQAGgIALgGQAGgDAGgBIAOgDIAAgOIgBgKQAAgEgBgCQgCgEgDgBQgDgDgFAAQgGAAgEAFQgEAEAAAFIAAABIAAAEIAAACQAAAFgCACQgCADgDAAQgDAAgCgDQgCgCAAgDQAAgJAFgFQADgHAIgEQAGgDAIAAQAIAAAGADQAGADAEAHQACAEABAGQABAFAAAJIAAAvQAAANACAEQACAEADAAIACAAIACgBIAAAGIgFACIgEAAQgHAAgDgEQgEgFgBgLQgDAMgHAEQgFAFgJAAQgLAAgGgKgADKAWQgJAJAAANQABAKAEAGQAEAGAHAAQAIAAAGgJQADgIAAgSIAAgVQgRAFgHAHgAidBCQgHgGAAgOQAAgMAFgHQAFgIAKgGQAGgDAHgBIAOgDIAAgOIAAgKQgBgEgCgCQgCgEgDgBQgDgDgEAAQgGAAgFAFQgFAEAAAFIAAABIABAEIAAACQAAAFgCACQgBADgDAAQgEAAgCgDQgBgCAAgDQAAgJADgFQAGgHAGgEQAHgDAHAAQAIAAAHADQAGADADAHQADAEAAAGQABAFAAAJIAAAvQAAANACAEQABAEAEAAIADAAIADgBIAAAGIgGACIgFAAQgGAAgDgEQgEgFgBgLQgEAMgGAEQgFAFgJAAQgMAAgGgKgAiOAWQgJAJAAANQABAKAEAGQAEAGAIAAQAIAAAEgJQAFgIAAgSIAAgVQgRAFgIAHgAnyA9QgKgRAAgZQAAgSAFgMQAEgMAJgIQAHgGALAAQAPAAAJAOQAIANABAbIg2AAIABATIADAMQABAKAGAFQAGAFAIAAQAIAAAGgHQAHgIACgQIAGAAQgCASgIALQgJAKgOAAQgQAAgKgPgAnGAIQAAgTgFgLQgEgKgKAAQgIABgFAJQgEALgCATIAmAAIAAAAgAvpBCQgIgGABgOQgBgMAFgHQAFgIALgGQAGgDAHgBIANgDIAAgOIAAgKQgBgEgBgCIgEgFQgEgDgEAAQgIABgDAFQgEADAAAGIAAABIAAADIABACQAAAFgDACQgCADgDAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBgBQgCgCAAgDQAAgJAFgFQADgHAIgEQAFgDAKAAQAHAAAGADQAGADAEAHIAEAKQABAFAAAJIAAAvQAAANACAEQAAAEAEAAIACAAIADgBIAAAGIgGACIgDAAQgIAAgDgEQgEgFgBgLQgDAMgGAEQgGAFgJAAQgLAAgGgKgAvaAWQgIAJAAANQABAKADAGQAEAGAHAAQAKAAAEgJQADgIAAgSIAAgVQgRAFgHAHgAOKBJIgLAAIgIAAIgLABIAAgEQAHAAACgEQADgBAAgIIAAg5IgBgLQAAgDgCgEQgCgFgDgCQgDgBgFAAQgFgBgEADQgDACgDAFQgCADAAAFQgCAFAAAFIAAA4QAAAIACABQAEAEAGAAIAAAEIgKgBIgJAAIgJAAIgLABIAAgEQAIgCADgCQACgBAAgJIAAhGQAAgHgBgCQgBgDgCgBIgJgBIAAgFIANgCIAKgFIABAIIABANQAFgKAHgFQAFgDAIAAQAHAAAGADQAFAEAFAHIADAKIABAOIAAA3QgBAJAEABQABACAJACIAAAEIgKgBgALWBJIgJAAIgJAAIgMABIAAgEQAJgCABgCQAEgBAAgJIAAhIQAAgIgCgCQgDgDgJAAIAAgFIAPgBIAMgDIAABeQAAAJAEABQABACAJACIAAAEIgLgBgAHXBJIgJAAIgJAAIgLABIAAgEIAIgCQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAIAAgCIgCgFIgPggIgRAeIgCAGIgBADQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAQACADAGAAIAAAEIgIgBIgDAAIgEAAIgEAAIgDAAIgIABIAAgEQAEAAADgDQADgBABgCIAGgJIAUgjIgTgqQgBgEgFgCQgCgEgHAAIAAgEIALACIAIAAIAIAAIALgCIAAAEQgEAAgCACIgBAEIAAABIABAEIALAYIANgXIADgEIABgCQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgEgCgDAAIAAgEIAIACIAGAAIAGAAIAJgCIAAAEQgFAAgDACQgCABgCADIgEAEIgSAgIAWAvQABAFACADQACADAEAAQACACAEAAIAAAEIgKgBgACfBJIgIAAIgJAAIgMABIAAgEQAHAAAEgEQACgBgBgIIAAg6QAAgOgDgGQgDgFgIAAQgJAAgFAGQgEAIAAAMIAAA5QAAAIACABQADAEAGAAIAAAEIgJgBIgKAAIgIAAIgKABIAAgEQAGAAADgEQADgBAAgIIAAg5IgBgLQAAgFgCgCQgCgFgCgCQgDgBgFAAQgFAAgEACQgDACgDAGQgCAEAAAEIgBAKIAAA3QAAAIACABQACAEAHAAIAAAEIgKgBIgJAAIgJAAIgLABIAAgEQAJgCABgCQADgBAAgJIAAhGIAAgJIgBgDIgCgBIgKgBIAAgFIAOgCIAKgFIACAKIAAAKQAGgKAFgEQAGgDAHAAQAJAAAFADQAGAFADAKQAFgLAFgEQAFgDAKAAQAHAAAFADQAGADADAIQACADAAAGQACAFAAAJIAAA4QAAAJABABQADACAIACIAAAEIgLgBgAkxBJIgIAAIgJAAIgKABIAAgEQAFAAAEgEQADgBgBgIIAAg6QAAgOgDgGQgFgFgGAAQgKAAgFAGQgDAIAAAMIAAA5QAAAIACABQACAEAHAAIAAAEIgKgBIgJAAIgIAAIgLABIAAgEQAGAAAEgEQACgBAAgIIAAg5IgBgLIgBgHIgFgHQgDgBgFAAQgEAAgFACQgDACgCAGQgCAEgBAEIgBAKIAAA3QAAAIADABQACAEAHAAIAAAEIgLgBIgJAAIgJAAIgLABIAAgEQAJgCACgCQADgBAAgJIAAhGIAAgJQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgDgBIgIgBIAAgFIANgCIALgFIAAAKIABAKQAFgKAGgEQAGgDAIAAQAIAAAFADQAGAFADAKQAEgLAGgEQAGgDAJAAQAHAAAGADQAGADACAIIADAJIABAOIAAA4QgBAJACABQADACAIACIAAAEIgLgBgAoRBJIgIAAIgJAAIgLABIAAgEQAIgCACgCQADgBAAgJIAAhIQAAgIgDgCQgCgDgIAAIAAgFIANgBIAOgDIAABeQAAAJACABQADACAIACIAAAEIgMgBgApABJIgIAAIgJAAIgLABIAAgEQAHAAADgEQACgBAAgIIAAg5IgBgLIgBgHQgDgFgEgCQgCgBgGAAQgDgBgFADQgEACgCAFIgEAIIAAAKIAAA4QAAAIADABQACAEAGAAIAAAEIgLgBIgIAAIgKAAIgKABIAAgEQAIgCACgCQAEgBgBgJIAAhzQABgJgEgDQgBgBgJAAIAAgGQAHABAIgCIANgEIAAA9QADgIAHgEQAFgDAIAAQAHAAAFADQAGAEAEAHQADAFAAAGIABANIAAA3QAAAJACABQAEACAHACIAAAEIgLgBgAr2BJIgJAAIgIAAIgLABIAAgEQAGAAADgEQADgBAAgIIAAg5IgBgLIgCgHQgCgFgDgCQgEgBgFAAQgEgBgFADQgDACgCAFQgCADgBAFQgCAFABAFIAAA4QgBAIADABQADAEAGAAIAAAEIgKgBIgJAAIgJAAIgKABIAAgEQAHgCACgCQAEgBgBgJIAAhGQAAgHgBgCQAAgDgDgBIgIgBIAAgFIANgCIALgFIABAIIAAANQAFgKAGgFQAGgDAIAAQAGAAAHADQAEAEAFAHQADAFABAFIAAAOIAAA3QAAAJADABQACACAIACIAAAEIgLgBgAuDBJIgJAAIgJAAIgLABIAAgEQAIgCACgCQADgBAAgJIAAhIQAAgIgCgCQgDgDgIAAIAAgFQAHABAHgCIAOgDIAABeQgBAJADABQADACAHACIAAAEIgLgBgAwYBJIgIAAIgJAAIgMABIAAgEQAIgCADgCQADgBgBgJIAAhHQABgGgBgEQgBgCgDgBIgJgBIAAgFQAHABAHgCIAKgDIABAGIAAAHIAAAIQAEgKAFgGQAHgFAGABQAHgBAFAFQAEAFAAAJQABAFgDADQgCADgDAAQgDgBgDgBQgCgCgBgEIAAgBIACgEIAAgCQAAAAgBgBQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAQgHAAgEAKQgEAKgBARIAAAvQAAAJADABQAEACAHACIAAAEIgMgBgAxeBJIgKgBIgLABIgMABIAAgGIAJgCQAEAAABgDQACgEgBgFIAAh/IgJAAQgHAAgEACQgEADgDAGQgDAHgCAKIgEAAIAFgjIBPAAIAFAjIgFAAQgCgKgDgHIgGgJQgEgCgGAAIgMAAIAAB/QAAAFABAEQABADAEAAIAJACIAAAGIgMgBgAPFBJIAAgGIAKgBQADgBACgDIABgJIAAhwQAAgHgBgCQgCgEgDAAQgCgCgIAAIAAgGIBQAAIACAjIgDAAQgDgQgFgHQgFgFgKAAIgYAAIAABAIAYAAQAHAAACgEQADgFAAgKIAEAAIAAAsIgEAAQAAgLgDgFQgDgCgGAAIgYAAIAAA3QgBAIACACQADADAHAAIANAAQAHAAAFgCQAFgCADgIIAEgSIAFAAIgFAlgAvUg1IAAgPIAGAAIAEgBIACgCIABgCIABgFQAAgDgCgCQgDgDgDAAIgFAAIgGADIgCgHIAIgEIAIgBQAIABAEAEQAFAGAAAGQAAAJgEADQgDAEgHAAIgCAAIgDAAIAAAJgAMhg2IgTgTIgTATIgJAAIAXgiIAJAAIAYAigADpg2IgTgTIgVATIgHAAIAXgiIAIAAIAZAigAiMg2IASgiIATAAIgcAigAnFg2IgTgTIgTATIgJAAIAYgiIAJAAIAYAigALGg7QgEgDAAgGQAAgFAEgFQABgCAFAAQAEAAADACQADAFAAAFQAAAGgDADQgDAEgFAAQgEAAgBgEgAohg7QgCgDAAgGQAAgFACgFQACgCAFAAQAEAAADACQACAFAAAFQAAAGgCADQgDAEgFAAQgEAAgCgEgAuUg7QgCgDAAgGQAAgFACgFQADgCAFAAQADAAAEACQACAFAAAFQAAAGgCADQgEAEgEAAQgFAAgCgEgADehcIgGgDIgGgFIgEgEIgEgBQgEAAgCACQgDADgCAGIgEgCIACgLIACgGIAGgEIAGgBIAEAAIAFADIAHAGQADACACAAIADACQAEAAACgDQADgCABgHIAGABIgCALIgEAHIgFAFIgHACIgDgBg");
	this.shape.setTransform(93.55,11.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.8,-0.7,234.70000000000002,23.9);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.h3();
	this.instance.setTransform(-70,-15,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70,-15,320,198);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.h2();
	this.instance.setTransform(-65,-28,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65,-28,297,213);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3E8DCA").s().p("Ap8BuIgJAAIgIAAIgMABIAAgFQAIAAADgCQADgDAAgHIAAh4QAAgHgCgCQgBgDgDgBIgIAAIAAgGIAJgBQAFAAADgBIAHgBIACAIIAAAMQAEgLAHgFQAEgEAIAAQAKAAAHAIQAIAGAFAOQAEAMAAARQAAAQgEANQgEAOgIAHQgIAIgJAAQgHAAgGgFQgEgDgGgLIAAAuQAAAHADADQADACAGAAIAAAFIgKgBgAp4gcQgFAMgBAWQABAbAFANQAFAOAKAAQAKAAAFgNQAFgNAAgYQAAgZgFgNQgGgNgKgBQgJAAgFAOgAHUBqQgJgDgEgIQgEgGgBgLQAAgIAFgHQAEgHAIgEIgHgFQgCgEAAgDQAAgHAEgFQAFgFAKgDQgKgEgFgIQgGgJABgMQgBgPAJgLQAIgJAPAAIAKABIAJAEIAXAAIAAAKIgRgBIADAKIACALQgBAIgDAHQgCAIgGAFIgEACIgHADIgJAEIgLADIgGAFIgBADIABAFQAAAAABAAQAAABABAAQAAAAABAAQABAAABABIALABIAMAAIAJADIAGADQAHADADAHQAEAHAAAIQAAAMgEAIQgFAHgIAFQgKAEgLAAQgMAAgIgEgAHQBBQgGAGgBAJQABAHADAFQAEAFAGADQAIACAIABQANgBAJgFQAFgGAAgLQAAgJgFgGQgJgEgPAAQgNAAgIAEgAHbgjQgFAIAAAOQAAANAFAIQAFAIAHAAQAIAAAFgIQAEgIAAgNQAAgPgEgHQgFgHgHgBQgJABgEAHgAE1BqQgDgEgBgFQABgGADgDQADgFAEAAQAEAAADAFQADADAAAGQAAAFgDAEQgDAEgEAAQgEAAgDgEgAQQA4QgMgJgGgSQgFgSAAgZQAAgZAFgRQAGgSAMgLQALgJAOAAQAJAAAGADQAHAEAHAGIAHgOIADAAIAAAvIgEAAIgDgMIgDgJQgFgJgHgEQgHgFgHAAQgRAAgKATQgIASAAAkQAAAlAIASQAJATARABQAHgBAFgCQAFgDAHgEIAAgoQAAgHgCgCQgEgCgHAAIAAgGIALACIAIAAIAKAAIALgCIAAAGIgJAAIgDAEIgBAHIAAAnQgMAJgIAEQgKAEgKAAQgOAAgLgLgAKWA7QgHgHgFgMQgDgNAAgSQAAgRADgMQAFgPAIgGQAJgIAKABQAKgBAIAIQAHAIAFAOIADgIIABgIIgBAAIgCAAQgDAAgCgCQgDgCAAgFQAAgFADgEQADgCAEAAQAEAAADADQADAEAAAIQAAAFgCADIgDAKIgGAMIgBAAQACAEAAAFIABAJQgBARgEANQgFAOgHAHQgHAIgLAAQgLAAgIgIgAKagcQgHANAAAYQAAAaAHANQAFANAKAAQAKAAAEgNQAGgNAAgZQAAgagGgMQgEgPgKAAQgJAAgGAPgAJOA8QgJgIgDgMQgFgMABgSQgBgSAFgMQAEgPAJgGQAHgIAMABQAFgBAEACQAFACADAGIAFgNIADAAIAAApIgEAAIgCgLIgCgGQgCgHgFgEQgFgEgFAAQgJAAgHAPQgEANAAAZQAAAYAEAMQAFANALAAQARAAACgfIAIAAQgCAUgHAIQgIALgLAAQgLAAgIgHgAEqA7QgIgHgEgMQgFgNAAgSQAAgRAFgMQAFgPAHgGQAIgIAKABQAKgBAJAIQAIAGAEAPQADAMAAASQAAARgEALQgEAOgJAHQgHAIgKAAQgLAAgHgIgAEtgcQgFANAAAYQAAAaAFANQAFANAJAAQALAAAFgNQAFgNAAgZQAAgagFgMQgFgPgKAAQgJAAgGAPgADTA8QgIgIgEgMQgFgNABgRQgBgRAFgMQAEgOAIgGQAHgJAJABQAHAAAFADQAFAFAFALIAAgfIgWAAIAAgIIAWAAIAAgEQAAgIgDgDQgCgCgIAAIAAgEIAPgDIAMgDIAAAbIANAAIAAAIIgNAAIAABlIAAAKQABADAEABIAIABIAAAEIgKABIgGABIgIAEIgBgLIAAgIQgEAJgGAFQgFAFgIAAQgKAAgHgHgADRAKQAAAYAFANQAFANALABQAIgBAGgMQAFgNAAgZQAAgYgFgOQgGgMgKAAQgTAAAAAygABZAyQgKgPAAgbQAAgQAEgMQAFgPAIgGQAIgHALAAQAOAAAJANQAIAPAAAaIg0AAIABATQAAAJACAEQADALAFAFQAGAFAGAAQAKAAAGgJQAFgHACgPIAHAAQgBASgJAKQgJALgNAAQgRAAgJgRgACFgBQgBgVgFgLQgEgJgJgBQgIABgFAJQgHALAAAVIAnAAIAAAAgAhRA/QgEgDgDgHIgCgJIAAgMIAAhFIgLAAIAAgIQAIAAAFgJQAGgIACgRIAFAAIAAAhIAVAAIAAAJIgVAAIgBBEQAAAOACAGQAEAGAFAAIAFgBIAHgEIAAAHQgFAEgFACQgEACgEAAQgGAAgEgEgAinAyQgIgPgBgbQABgQAEgMQADgPAJgGQAHgHAKAAQARAAAIANQAJAPAAAaIg2AAIABATIACANQAEALAFAFQAEAFAJAAQAIAAAGgJQAGgHABgPIAIAAQgCASgIAKQgJALgNAAQgQAAgLgRgAh7gBQAAgVgFgLQgEgJgKgBQgHABgFAJQgGALgBAVIAmAAIAAAAgAlbA/QgEgDgDgHIgCgJIgBgMIABhFIgMAAIAAgIQAKAAAFgJQAFgIADgRIAEAAIAAAhIAVAAIAAAJIgVAAIAABEQAAAOACAGQADAGAFAAIAFgBIAHgEIAAAHQgEAEgGACQgDACgEAAQgHAAgEgEgAncA6QgFgJgCgNQAAgLAGgIQAFgHAKgGIAMgFIAPgDIAAgOIAAgKIgDgHQgCgDgDgBQgDgCgEgBQgGABgFAEQgEADAAAGIAAAGQAAAFgCACQgBAEgFAAQgCAAgCgDIAAgGQAAgIACgHQAFgFAGgEQAHgEAJAAQAHAAAGADQAHAEADAGIACAKQACAHAAAJIAAAvQAAAMABAEQACAFAEAAIABAAIADgBIAAAGIgFABIgFACQgGAAgDgGQgDgEgBgLQgEALgGAEQgGAGgJAAQgKAAgIgJgAnLANQgJAJAAANQAAAJAEAGQAEAHAIgBQAIABAFgJQAEgIAAgSIAAgVQgRADgHAJgAuNA6QgHgJgBgNQAAgLAGgIQAFgHAKgGIANgFIANgDIAAgOIgBgKIgBgHQgCgDgDgBQgCgCgEgBQgHABgEAEQgEADgBAGIAAAGQABAFgCACQgCAEgEAAQgDAAgCgDIAAgGQAAgIADgHQAEgFAGgEQAIgEAIAAQAHAAAGADQAGAEADAGQADAFACAFQABAHAAAJIAAAvQAAAMAAAEQACAFAEAAIADAAIACgBIAAAGIgFABIgGACQgGAAgDgGQgEgEAAgLQgFALgFAEQgFAGgJAAQgLAAgHgJgAt9ANQgJAJABANQAAAJADAGQAFAHAGgBQAKABAEgJQAEgIgBgSIAAgVQgQADgHAJgAPnA/IgHAAIgGAAIgLAAIgNACIAAgGQAJAAADgDQADgDAAgFIgCh9IgdBoIgCAJIgBAHIgEAJIgCAIIgCAAIgmiKIgFB7QAAAIAEACQADAEAIAAIAAAGIgJgBIgIgBIgIABIgLABIAAgGQAHgBADgBQADgBABgEIACgJIADh0QAAgHgCgDQgDgCgKgCIAAgGIAIACIAHAAIAIAAIAJgCIAiB2IAhh2IAKACIAIAAIAGAAIAHgCIAAAGQgIABgCADQgFADABAHIACB0QAAAHACACQAAADADACIAJACIAAAGIgIgCgANaA/IgKAAIgLAAQgEAAgIACIAAgGQAHAAADgDQADAAgBgEIAAgDIAAgGIgHgYIgpAAIgGAWIgCAGIAAAFQgBADADACQACABAHABIAAAGIgJgBIgJgBIgGABIgKABIAAgGQAFAAADgCQAEgBACgEIADgJIAqiLIAkCMQABAGACADQACADADABQACABAHABIAAAGQgHgCgFAAgAM9ALIgThHIgTBHIAmAAgAG0A/IgJAAIgJAAIgKACIAAgEQAGgBACgDQAEgDAAgGIAAg5QAAgHgBgEQgBgFgCgDQgCgFgCgCQgDgDgFABQgFAAgEACQgEACgCAFIgDAIIgBAMIAAA4QgBAGADADQADADAGABIAAAEIgKgCIgJAAIgIAAIgLACIAAgEQAIgBACgDQADgCgBgIIAAhHIAAgLQgBgCgDgBIgIgBIAAgFIAOgCIALgEIABAIIAAANQAFgLAGgEQAFgEAIAAQAGAAAHADQAFAFAEAGIADAMIABANIAAA4QAAAIACACQADADAIABIAAAEIgLgCgABEBAIgFAAIgFAAIgHABIgag9IgNAQIAAAbQAAAIADACQACADAIABIAAAEIgKgCIgJAAIgIAAIgMACIAAgEQAIgBADgDQADgCAAgIIAAh1QAAgIgDgEQgDgCgIAAIAAgEIAOgDIAMgDIAABoIAegnIACgFIAAgCQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAQgCgCgFgBIAAgFIAJABIAHAAIAJAAIAJgBIAAAFIgHACQgDABgDACIgFAHIgRAWIAaA3IADAIIAFAEQADABAEABIAAAEIgHgBgAjCA/IgIAAIgIAAIgMACIAAgEQAIgBACgDQADgCAAgIIAAhJQAAgIgDgDQgCgCgIAAIAAgFIAOgCIAOgEIAABhQgBAIADACQACADAJABIAAAEIgNgCgAjsA/IgIAAIgKAAIgLACIAAgEQAHgBAEgDQABgDAAgGIAAg5IAAgMIgBgHQgEgFgCgCQgEgDgFABQgEAAgFACQgDACgDAFIgDAIIgBAMIAAA4QAAAGADADQACADAHABIAAAEIgLgCIgIAAIgJAAIgKACIAAgEQAHgBADgDQADgCAAgIIAAh1QAAgIgDgEQgDgCgHAAIAAgEIAOgDIAMgDIAAA9IAKgLQAGgEAHAAQAIAAAFAEQAGAEADAGQADAGABAGIABANIAAA4QAAAIADACQACADAHABIAAAEIgKgCgAnyA/IgJAAIgJAAIgLACIAAgEQAGgBAEgDQACgDAAgGIAAg5IAAgMIgCgHQgDgFgDgCQgDgDgFABQgFAAgEACQgDACgDAFQgDAEAAAEIAAAMIAAA4QgBAGACADQADADAHABIAAAEIgLgCIgJAAIgIAAIgLACIAAgEQAIgBADgDQACgCAAgIIAAh1QAAgIgCgEQgDgCgIAAIAAgEIAOgDIAOgDIAAA9QAEgGAFgFQAGgEAHAAQAGAAAHAEQAFAEAFAGIACAMQABAFAAAIIAAA4QgBAIAFACQABADAJABIAAAEIgLgCgArOA/IgIAAIgJAAIgLACIAAgEQAIgBADgDQACgDgBgGIAAg7QAAgPgDgGQgEgFgGAAQgKAAgFAHQgEAIAAANIAAA5QAAAGACADQADADAHABIAAAEIgLgCIgIAAIgIAAIgLACIAAgEQAHgBADgDQACgDAAgGIAAg7IgBgLQAAgFgBgBQgCgFgCgCQgFgCgDAAQgFAAgEACQgEADgDAFIgCAIIAAALIAAA4QAAAGACADQADADAGABIAAAEIgLgCIgIAAIgJAAIgKACIAAgEQAHgBADgDQAEgCgBgIIAAhHIAAgJIgCgEIgDgBIgIgBIAAgFIANgCIAKgEIABAKIAAAKQAFgJAHgFQAGgEAGAAQAJAAAGAEQAEAEAEALQAEgLAGgEQAFgEAJAAQAIAAAGADQAFAFADAFQABAFABAFIAAAOIAAA6QAAAIACACQAEADAHABIAAAEIgLgCgAukA/IgIAAIgKAAIgLACIAAgEQAJgBACgDQACgDAAgGIAAg5IgBgMIgBgHQgCgFgEgCQgEgDgEABQgFAAgEACQgDACgDAFIgDAIIgBAMIAAA4QgBAGAEADQABADAHABIAAAEIgKgCIgIAAIgJAAIgLACIAAgEQAIgBADgDQADgCgBgIIAAh1QABgIgDgEQgDgCgIAAIAAgEIAOgDIANgDIAAA9QAFgGAFgFQAGgEAGAAQAIAAAGAEQAFAEAEAGIADAMQACAFAAAIIAAA4QgBAIADACQACADAIABIAAAEIgLgCgAv/A/IgLAAIgKAAIgNACIAAgGQAGAAAEgDQABAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBQAAAAAAAAQAAAAAAgBQAAAAAAgBQgBAAAAAAIgCgHIggg8IgHAKIAAAyIABAJQAAAEAEABQACABAHABIAAAGQgHgCgFAAIgKAAIgGAAIgHAAIgJACIAAgGIAKgCQADgCABgDQACgCgCgHIAAhyQACgGgCgEQgBgDgDgBIgKgCIAAgGIANACIAJAAIAKAAIAMgCIAAAGQgHABgCABQgDABgBADIgBAKIAAA2IApg7IACgDIAAgDQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgCgBgHgBIAAgGIAKACIAJAAIAHAAIALgCIAAAGIgJACQgDAAgEAEIgGAHIgfAtIApBIQACAGADADQADAEADABQADACAGAAIAAAGQgIgCgFAAgAnKhAIASgjIAUAAIgeAjgAt7hAIASgjIATAAIgdAjgAFPhAIgTgVIgTAVIgJAAIAYgjIAIAAIAYAjgACGhAIgTgVIgUAVIgIAAIAXgjIAIAAIAOAUIAPgfIAUAAIgdAkIgEAAIAIAKgAh6hAIgUgVIgSAVIgJAAIAYgjIAJAAIAMAUIAQgfIAUAAIgdAkIgDAAIAGAKgAjRhGQgEgEAAgFQAAgGAEgEQACgDAEAAQAFAAACADQACAEAAAGQAAAFgCAEQgCAEgFAAQgEAAgCgEg");
	this.shape.setTransform(86.9,-49.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.9,-60.9,223.6,22.199999999999996);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4
	this.instance = new lib.bg2();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,320,480);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.tagline();
	this.instance.setTransform(197,38,0.36,0.36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_2
	this.instance_1 = new lib.light();
	this.instance_1.setTransform(-47,-7,0.78,0.78);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-47,-7,756.6,195);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABrCzQgHgIgBgQIANAAQABALAFAHQAIAIAOAAQAKAAAHgFQAHgGAAgJQAAgJgHgGQgEgEgOgGQgTgIgGgFQgLgJAAgOQAAgOAMgJQAJgIAPAAQAUAAAKAOQAFAHABAMIgNAAQgBgJgFgFQgGgHgMAAQgJAAgFAEQgIAGAAAIQAAAIAIAFQAEADARAHIARAJIAJAHQAHAJAAAMQAAARgNAKQgKAHgQAAQgWAAgKgOgAkKCyQgPgRAAgdQAAghARgRQANgNATAAQARAAALAJQAKAKACARIgMAAQgGgYgWAAQgPAAgJANQgLAOAAAXQAAAZAMAPQAJAKAOAAQANAAAIgHQAHgIACgQIAMAAQgBAQgGAKQgLARgXAAQgWAAgNgPgAILC/IAAgKIA9hiIg5AAIAAgMIBJAAIAAAKIg9BjIA8AAIAAALgAHsC/Ig6hjIAABjIgMAAIAAh4IAOAAIA6BkIAAhkIANAAIAAB4gAFRC/IAAh4IBCAAIAAAMIg1AAIAAAoIAxAAIAAAMIgxAAIAAAtIA2AAIAAALgADzC/IAAh4IAWAAQAUAAAJADQAJADAFAIQAFAHAAAJQAAAUgUAGQAaAHAAAYQAAAPgKAJQgGAGgJACQgJABgVAAgAEAC0IAMAAIAQgBQAGAAAEgCQAFgCADgGQADgFAAgHQAAgHgEgGQgEgFgGgDQgHgCgQAAIgMAAgAEAB7IALAAQAQAAAHgEQAJgFAAgMQAAgGgDgFQgDgEgFgCQgGgCgPAAIgLAAgAAUC/IAAh4IBCAAIAAAMIg0AAIAAAoIAwAAIAAAMIgwAAIAAAtIA1AAIAAALgAhWC/IAAh4IATAAIAYABQAVADAMASQALAQAAAWQAAAZgMAQQgNAQgVACIgYABgAhJC0IAJAAQAOAAAGgCQAGgBAHgEQAJgFAFgLQAFgLAAgPQAAgVgLgOQgJgKgOgCIgVgBIgGAAgAirC/IAAh4IBCAAIAAAMIg1AAIAAAoIAxAAIAAAMIgxAAIAAAtIA2AAIAAALgAkwC/IgfgzIgUAAIAAAzIgOAAIAAh4IAVAAIAVABQAHABAGACQAKAEAFAJQAEAIAAAJQAAAYgZAJIAgA1gAljCAIAIAAIAQAAIAIgCQAOgFAAgQQAAgOgLgFIgKgDIgRAAIgIAAgAnGC/IAAh4IBCAAIAAAMIg0AAIAAAoIAwAAIAAAMIgwAAIAAAtIA1AAIAAALgAnsC/IAAhqIgjBqIgNAAIgjhqIAABqIgNAAIAAh4IAVAAIAhBpIAihpIAUAAIAAB4gAC3CXIAAgKIAxAAIAAAKgAOKATQgDgEAAgEQAAgFADgDQAEgDAEAAQAFAAADADQADADAAAFQAAAEgDAEQgDADgFAAQgFAAgDgDgAHgATQgDgEAAgEQAAgFADgDQAEgDAFAAQAEAAADADQAEADAAAFQAAAEgEAEQgDADgFAAQgEAAgEgDgAMLgXQgIgIgBgMIAAgTIAAhHIANAAIAABGIABATQAAAFADAEQADAGAHADQAGADAJAAQAKAAAIgFQAJgFABgOIABgQIAAhGIANAAIAABHIAAATQgBAFgCAEQgEALgLAGQgKAGgOAAQgVAAgMgMgAD8gZQgQgRAAgfQAAgfAQgRQAGgHAJgDQAJgEALAAQAQAAALAJQAKAJACARIgMAAQgDgLgFgFQgHgHgNAAQgPAAgJAKQgLAOAAAaQAAAbANANQAJAKAPAAQAPAAANgIIAAgeIgZAAIAAgMIAlAAIAAAxQgRANgXAAQgXAAgNgOgAgFgUQgLgJAAgPQAAgOALgLIAMgMQgIgLgCgFQgDgFAAgGQAAgLAHgGQAHgHAMAAQAKAAAGAFQAIAHAAALQAAAIgFAHQgEAHgLAJIAZAiQAFgIAAgQIALAAIAAADQAAAKgCAHQgCAIgEAGIAPAVIgOAAIgJgMQgFAGgGADQgIAEgLAAQgPAAgJgIgAADg9QgGAHAAAKQAAAJAFAGQAHAGALAAQANAAAJgLIgbglQgIAGgEAEgAAKh2QgEADAAAGQAAAEABAEIAKAOQAIgGAEgGQADgFAAgGQAAgFgDgDQgEgEgGAAQgFAAgEAEgAPjgNIAAhtIgfAAIAAgLIBMAAIAAALIgfAAIAABtgAOzgNIgKggIgtAAIgLAgIgOAAIAph5IAMAAIApB5gAN/g5IAmAAIgTg7gALcgNIAAg5Ig4AAIAAA5IgOAAIAAh4IAOAAIAAAzIA4AAIAAgzIAOAAIAAB4gAJbgNIAAhtIgfAAIAAgLIBMAAIAAALIgfAAIAABtgAHLgNIAAh4IBCAAIAAALIg1AAIAAApIAxAAIAAALIgxAAIAAAtIA2AAIAAAMgAGkgNIAAg5Ig5AAIAAA5IgNAAIAAh4IANAAIAAAzIA5AAIAAgzIANAAIAAB4gADKgNIg6hkIAABkIgMAAIAAh4IAOAAIA6BkIAAhkIANAAIAAB4gAiFgNIAAh4IBCAAIAAALIg1AAIAAApIAxAAIAAALIgxAAIAAAtIA2AAIAAAMgAiigNIgegzIgeAzIgQAAIAmg/Igkg5IAQAAIAcAuIAcguIAPAAIgjA5IAlA/gAkwgNIAAhrIgjBrIgNAAIgjhrIAABrIgNAAIAAh4IAVAAIAhBpIAihpIAUAAIAAB4gAmsgNIgLggIgtAAIgLAgIgOAAIAqh5IAMAAIApB5gAngg5IAmAAIgTg7gApBgNIAAh4IAOAAIAABsIAzAAIAAAMgAqSgNIg6hkIAABkIgMAAIAAh4IAOAAIA6BkIAAhkIANAAIAAB4gAstgNIAAh4IBCAAIAAALIg1AAIAAApIAxAAIAAALIgxAAIAAAtIA2AAIAAAMgAtVgNIAAh4IAOAAIAAB4gAt0gNIgfg0IgUAAIAAA0IgOAAIAAh4IAVAAIAVABQAHAAAGADQAKADAFAKQAEAHAAAKQAAAYgZAIIAgA2gAunhMIAIAAIAQgBIAIgCQAOgEAAgQQAAgPgLgFIgKgCIgRgBIgIAAgAvwgNIAAhtIgfAAIAAgLIBMAAIAAALIgfAAIAABtgAOkiRIgSgQIgSAQIgMAAIAXgYIAOAAIAYAYgAH+iRIgSgQIgSAQIgMAAIAXgYIAPAAIAXAYgAr6iRIgSgQIgSAQIgMAAIAXgYIAPAAIALALIAAgIIACAAQANAAAAgJQAAgEgDgCQgCgDgFAAIgKACIAAgHQAIgDAGAAQAIAAAFAEQAGAEAAAIQAAAIgHAEQgFADgJAAIAAAIIgDAAIAIAIgAnqiWIADgJQAFgIAIAAQAGAAAIAFIAIAEIAEABQAHAAACgLIAIADQgBAGgCADQgCAEgEADQgEACgEAAIgGgBIgJgFQgHgEgDAAQgHAAgCAKg");
	this.shape.setTransform(104.275,5.325);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.3,-14,208,38.7);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ak8BHQgJgGAAgLQAAgKAHgFIALgGQgJgDAAgGQAAgHAGgEIAJgEQgRgHAAgRQAAgOALgJQAHgGAOAAQAGAAAHACIAagBIAAAKIgRgBQAHAIAAAMQAAANgIAFQgFAFgPADQgKABgDACQgFADAAADQAAADADABIAOACQANABAFACQAUAEAAASQAAAOgLAHQgKAGgRAAQgTAAgLgIgAkyAqQgHAEAAAIQAAAGAHAEQAIAFAMAAQAOAAAIgGQAEgEAAgFQAAgPgcAAQgKAAgIADgAksgdQgGAGAAAIQAAAIAFAFQAGADAHAAQAJAAAFgDQAFgFAAgIQAAgIgEgFQgGgGgJAAQgHAAgFAFgAhpBPIAAgMQAMAAAFgEQAFgEADgKIADgGIgehWIANAAIAYBHIAYhHIANAAIgcBPIgJAYQgKATgVAAIgEAAgAIzBHQgCgCAAgDQAAgEACgCQADgDADAAQADAAADADQACACAAAEQAAADgCACQgDADgDAAQgDAAgDgDgAIkAnQgHgGgCgKIgBgOIAAg0IAMAAIAAA0QAAANADAEQAEAHALAAQALAAAHgJQADgHAAgNIAAgvIANAAIAAAGIABgBIAEgEIACgFIgBAAIgDgCQgEgDABgFQACgDADgCIAGAAQADAAACAEQACAEgBAEQgDALgOALIAAAsIAAAJIAAAGQAAAGACAFIgMAAIgCgFIAAgGQgDAFgEADQgHAGgKAAQgKAAgIgGgAHFAjQgMgNAAgWQAAgWAMgNQAIgKANAAQALAAAHAEQADADAEAHIAAgvIAMAAIAABeQAAAVACAFIgMAAQgCgFAAgEIAAgDQgDAGgEADQgGAGgLAAQgOAAgIgKgAHOgbQgIAKAAARQAAAQAHALQAFAGAKAAQAKAAAGgGQAHgLAAgQQAAgRgHgKQgFgIgLAAQgJAAgFAIgACyAnQgJgHAAgNQAAgSAVgGQALgFAVgDIAAgEQAAgIgDgEQgFgGgJAAQgRAAgCAPIgOAAQACgMAHgGQAIgHAQAAQAOAAAHAGQAHAEABAMIABALIAAAfQAAARACAGIgMAAQgCgFAAgGQgIAOgRAAQgMAAgIgGgADDADQgMAFAAAKQAAAHAFAFQAEAEAHAAQAOAAAFgKQAEgHAAgNIAAgIQgTAEgIADgAnrAnQgJgHAAgNQAAgSAUgGQALgFAVgDIAAgEQAAgIgDgEQgEgGgKAAQgRAAgDAPIgMAAQABgMAHgGQAIgHAQAAQAOAAAIAGQAGAEABAMIAAALIAAAfQAAARADAGIgMAAQgCgFAAgGQgIAOgRAAQgMAAgHgGgAnbADQgMAFAAAKQAAAHAFAFQAEAEAIAAQANAAAFgKQAEgHAAgNIAAgIQgTAEgIADgAAhAkQgCgDAAgDIAAg/IgNAAIAAgKIANAAIAAgZIANAAIAAAZIAUAAIAAAKIgUAAIAAArIAAAPQABAIAIAAQAGAAAHgDIAAALQgIADgIAAQgMAAgFgIgAFqAqIAAg0IgBgKQgCgOgOAAQgMAAgGAJQgDAGAAALIAAAyIgNAAIAAgyQAAgOgBgEQgEgIgLAAQgGAAgEACQgFADgDAEQgDAGAAAMIAAAxIgNAAIAAg6IAAgTIgCgIIAMAAQACAEAAAHQAIgNARAAQASAAAGAPQAJgPARAAQARAAAGAKQACAGABAIIAAALIAAA0gACIAqIAAgvQAAgPgDgFQgFgJgLAAQgMAAgGALQgDAGAAANIAAAuIgNAAIAAh4IANAAIAAAtQAJgMAPAAQAKAAAHAEQAIAFACAKIABATIAAAxgAiGAqIglguIAkgnIAQAAIgkAnIAnAugAi4AqIAAh4IANAAIAABKIAAAugAlkAqIAAgvQAAgPgCgFQgEgJgLAAQgNAAgGAKQgFAHAAAMIAAAvIgMAAIAAg4IAAgVIgCgIIAMAAQACAFAAAHQAJgOASAAQALAAAHAGQAHAGABAKIABAQIAAAxgApfAqIAAg6IgLAAIAAgJIALAAIAAg1IATAAIAYABQAWADAMARQAMARAAAXQAAAXgNARQgNAQgVACQgIABgRAAgApSAfIAJAAIATgBQAIgCAGgEQAHgFAEgGQAIgNAAgRQAAgWgKgOQgJgKgOgCIgWgBIgGAAIAAApIAeAAIAAAJIgeAAgAirgEgAnZg3IgHgEIgFgGIgCgHIAHAAQACAGAEACQAEACAEAAQAGAAADgCQAFgCAAgGIAHAAQAAAEgBAEIgGAFQgCADgEABQgDABgFAAIgHgBgAhMg5IAPgUIANAAIgTAUg");
	this.shape.setTransform(40.7917,13.225);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A7EBE").s().p("ArtCYIAAkvIXbAAIAAEvg");
	this.shape_1.setTransform(40.5,12.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.4,-2.8,149.9,30.400000000000002);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABLBjQAjgjATgjQgKAEgJAAQgUAAgNgPQgQgRAAgcQAAgbAOgRQAPgTAYAAQAWAAAPAQQAQASAAAdQAAAVgJAUQgJAUgVAYQgVAZgSAQgABchFQgHAOAAAaQAAAZAHAOQAHAOAPAAQAfAAAAgyQAAg4gfAAQgOAAgIANgALjBNQgNgNgCgaIAKAAQABAMADAIQAJATAYAAQASAAALgMQAJgLAAgRQAAgbgUgIQgJgDgQAAIgDAAIAAgJIADAAQAQAAAJgHQANgJAAgTQAAgOgHgIQgIgJgOAAQgTAAgKAOQgEAHgDAMIgIAAQAFgvAsAAQAXAAANAOQALALAAASQAAAPgJAKQgIAKgQAFQAOADAJAGQARAMAAAYQAAAWgQAPQgQAPgYAAQgYAAgNgNgAG4BCQgPgaAAgoQAAgUAFgRQAEgSAHgMQAOgXAbAAQARAAANALQAOALAHAZQAFAUAAAXQAAAlgNAaQgNAbgeAAQgcAAgOgYgAHMhEQgMAUAAAwQAAA0APATQAIALALAAQAhAAAAhSQAAgngIgVQgEgLgHgFQgGgGgIAAQgNAAgJAOgADVBWQgFgFAAgGQAAgHAFgEQAEgFAGAAQAHAAAEAFQAFAEAAAHQAAAGgFAFQgEAEgHAAQgGAAgEgEgAhMBCQgPgaAAgoQAAgUAFgRQAEgSAHgMQAOgXAbAAQARAAANALQANALAHAZQAFAUAAAXQAAAlgNAaQgMAbgeAAQgcAAgOgYgAg4hEQgMAUAAAwQAAA0APATQAIALALAAQAhAAAAhSQAAgngIgVQgEgLgHgFQgGgGgIAAQgNAAgJAOgAiaBWQgFgFAAgGQAAgHAFgEQAEgFAGAAQAHAAAEAFQAFAEAAAHQAAAGgFAFQgEAEgHAAQgGAAgEgEgAklBKQgQgSAAgcQAAgcAUgeQAKgPARgTQASgSATgQIAOAAQgmAjgTAiQAKgEAJAAQAVAAAOAPQAQARAAAcQAAAbgPASQgQASgYAAQgYAAgQgQgAkWgJQgIANAAAXQAAA3AgAAQAQAAAIgNQAIgOAAgaQAAgZgIgNQgHgPgQAAQgRAAgIAPgAqeBNQgNgNgBgaIAJAAQABAMAEAIQAIATAYAAQASAAALgMQAKgLAAgRQAAgbgUgIQgKgDgPAAIgDAAIAAgJIADAAQAQAAAJgHQANgJAAgTQAAgOgIgIQgHgJgPAAQgTAAgJAOQgFAHgCAMIgIAAQAEgvAtAAQAXAAAMAOQALALAAASQAAAPgIAKQgJAKgQAFQAPADAIAGQASAMAAAYQAAAWgQAPQgQAPgZAAQgXAAgOgNgAJBBYIAAgPQAfgjARgYQARgXAHgNQAHgOAAgKQAAgMgIgIQgIgJgNAAQgKAAgIAFQgIAEgEAHQgFAIgCAOIgJAAQACgYAIgLQAHgIAKgFQALgFANAAQATAAANAKQAHAGAEAIQAEAIAAAJQAAANgHANQgHAOgUAXIgvA3IBTAAIgDATgAEXBYIAAgPQAfgjARgYQARgXAHgNQAHgOAAgKQAAgMgIgIQgIgJgNAAQgKAAgIAFQgIAEgEAHQgFAIgCAOIgJAAQACgYAIgLQAHgIAKgFQALgFANAAQATAAANAKQAHAGAEAIQAEAIAAAJQAAANgHANQgHAOgUAXIgvA3IBTAAIgDATgAnIBYIAAgPQAfgjARgYQARgXAHgNQAHgOAAgKQAAgMgIgIQgIgJgNAAQgKAAgIAFQgIAEgEAHQgFAIgCAOIgJAAQACgYAIgLQAHgIAKgFQALgFANAAQATAAANAKQAHAGAEAIQAEAIAAAJQAAANgHANQgHAOgUAXIgvA3IBTAAIgDATgAs/BYIAAgPQAegjARgYQASgXAHgNQAGgOAAgKQAAgMgHgIQgJgJgNAAQgJAAgIAFQgIAEgFAHQgFAIgCAOIgJAAQADgYAIgLQAGgIALgFQALgFAMAAQAUAAAMAKQAHAGAFAIQAEAIAAAJQAAANgIANQgHAOgUAXIguA3IBSAAIgCATgAomAVIAAgMIBFAAIAAAMg");
	this.shape.setTransform(105.975,-61.075);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(22.8,-71,166.39999999999998,19.9);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMIBpIAAgMQANgBAHgEQAHgFAEgLIAIgSIgkhdQgCgHgDgCQgEgCgJAAIAAgFIAZABIAYgBIAAAFIgKABQAAABgBAAQAAAAgBABQAAAAAAABQAAAAAAABIABAGIAaBFIAahEIACgHQAAgCgDgCIgLgBIAAgFIASABIAVgBIAAAFQgJAAgDADQgEADgDAFIgtB1QgFAOgJAGQgIAHgNAAIgDAAgArNBlQgEgEAAgGQAAgGAEgEQAEgEAGAAQAFAAAEAEQAEAEAAAGQAAAGgEAEQgEAEgGAAQgFAAgEgEgAIXAxQgPgLgIgXQgFgQAAgUQAAgkARgYQAIgLAOgHQALgFAOAAQAWAAAQAOIAIgNIAEAAIAAAuIgFAAQgKgnggAAQgYAAgLAVQgLAVAAAgQAAAfAKATQALAXAYgBQATAAALgMQAKgMACgWIAIAAQgBATgGAMQgHANgNAHQgLAGgPAAQgTAAgQgMgAC2A8IAAiLIgBgJQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAgBQgEgBgJAAIAAgEQATgCARgEIAABBQAFgHAEgEQAIgHANgBQAUABAMAQQAMARAAAZQAAAZgNAQQgMARgUAAQgWAAgJgUIgLAUgADJACQAAAzAbAAQANAAAHgNQAHgOAAgZQAAgzgaABQgcgBAAA0gABPArQgMgQAAgZQAAgaANgQQANgRAVAAQAWAAAMARQAMARAAAZQAAAYgMARQgNARgWAAQgVAAgNgRgABegmQgHAOAAAaQAAA1AaAAQANAAAHgOQAHgNAAgaQAAg1gaAAQgNAAgHANgAhpAxQgQgLgIgXQgFgQAAgVQAAgkARgXQASgXAeABQAVAAARANIAKgOIAEAAIAAAvIgGAAQgEgNgEgIQgGgIgJgGQgJgEgLAAQgSAAgLALQgSASAAAtQAABMAuAAQAQAAARgKIAAgoQAAgEgCgCQgBgCgDAAQgEgCgJgBIAAgGIAbABIAbgBIAAAGQgLABgDACQgCACAAAGIAAAnQgdASgZgBQgUAAgQgLgAkXAsQgNgQAAgbQAAgZANgRQANgQAVAAQAOAAAKAIQAKAHAFANQAEAMAAAQIhHAAQABAXADAKQAIAUAUAAQAMAAAIgIQAIgIACgPIAKAAQgCAOgHAJQgMARgWgBQgXABgMgRgAkQgJIAzAAQgCgpgXAAQgXAAgDApgALPA0QgEgEgBgHQgCgHABgNIABhDIgQAAIAAgHQAWgBAHgiIAGAAIAAAhIAcAAIAAAJIgcAAIAABFQAAAOACAGQADAHAJAAQAGAAAKgEIAAAHQgNAHgLAAQgNAAgHgIgAEpA0QgKgJAAgNQAAgXAbgKQAQgGAUgDIAAgOQAAgMgEgFQgFgHgLAAQgJAAgFAEQgGAEAAAGIAAACIAAAEQAAAKgKAAQgHAAAAgIQAAgLAKgIQAMgKARAAQAKABAIADQAIAEAFAGQAGAIAAASIAAAwQAAAMACAFQACAFAFgBIAHgBIAAAHIgOABQgJAAgEgEQgEgFgBgLQgFAJgFAEQgIAIgPAAQgOAAgJgIgAFDACQgRAIAAASQAAAKAGAGQAFAFAJAAQANABAFgJQAGgIAAgTIAAgTQgRADgKAEgArnA0QgJgJAAgNQAAgXAbgKQAPgGAUgDIAAgOQAAgMgDgFQgFgHgLAAQgJAAgGAEQgFAEAAAGIAAACIAAAEQAAAKgKAAQgIAAAAgIQAAgLALgIQAMgKAQAAQAKABAJADQAIAEAFAGQAGAIAAASIAAAwQAAAMACAFQACAFAFgBIAGgBIAAAHIgNABQgJAAgEgEQgFgFgBgLQgFAJgEAEQgJAIgOAAQgPAAgJgIgArNACQgQAIAAASQAAAKAFAGQAGAFAJAAQAMABAGgJQAFgIAAgTIAAgTQgQADgLAEgAKZA6IgbABIAAgFQALAAADgDQAEgDAAgHIAAhLIgBgIQgBgEgDgBQgDgBgJAAIAAgEQATgCARgEIAABjIABAIQABACADABQAEACAIAAIAAAFIgbgBgAGgA6IgbABIAAgFQALAAADgDQAEgDAAgHIAAh4IgBgJQgBgDgDgBQgDgBgJAAIAAgEQASgCASgEIAACQIABAIQABACADABQAEACAIAAIAAAFIgbgBgAAgA6IgbABIAAgFQALAAADgDQAEgDAAgHIAAh4IgBgJQgBgDgDgBQgDgBgJAAIAAgEQASgCASgEIAACQIABAIQABACADABQAEACAIAAIAAAFIgbgBgAlGA6IgaABIAAgFQAJAAADgDQAEgDAAgHIAAg5QAAgPgEgGQgFgIgNgBQgMAAgIAKQgFAGAAAPIAAA4IABAIQABACADABQAEACAHAAIAAAFIgagBIgaABIAAgFQALAAADgDQADgDAAgHIAAh4IgBgJQgBgDgDgBQgDgBgJAAIAAgEQATgCARgEIAAA/QAMgQATgBQATABAKAPQAGAIAAASIAAA4IABAIQABACADABQAEACAIAAIAAAFIgagBgAnhA5IgeACIAAgGQAKgBAEgCQAEgBABgCIABgKIAAiDIgNAAQgPAAgGAKQgEAFgEAOIgGAAIAGgkIBpAAIAHAkIgGAAQgFgRgFgFQgGgHgMAAIgQAAIAACDQAAAHACADQABACADABQAEACAKABIAAAGIgegCgApvA6IgbABIAAgFQALAAADgDQAEgDAAgHIAAhLIgBgIQgBgEgDgBQgDgBgJAAIAAgEQATgCARgEIAABjIABAIQABACADABQAEACAIAAIAAAFIgbgBgAsyA5IgeACIAAgGQAKgBAEgCQADgBACgCIABgKIAAiDIgNAAQgPAAgHAKQgEAFgEAOIgGAAIAHgkIBpAAIAGAkIgFAAQgFgRgGgFQgGgHgMAAIgPAAIAACDQAAAHABADQABACAEABQAEACAKABIAAAGIgegCgAKPhOQgEgEAAgGQAAgFAEgEQAEgFAFAAQAGAAADAFQAEAEAAAFQAAAGgEAEQgDADgGAAQgFAAgEgDgAp5hOQgEgEAAgGQAAgFAEgEQAEgFAFAAQAGAAADAFQAEAEAAAFQAAAGgEAEQgDADgGAAQgFAAgEgDg");
	this.shape.setTransform(80.075,50.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.7,40.4,175.6,21);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Rectangl();
	this.instance.setTransform(-114,-36,0.7,0.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-114,-36,210,80.5);


(lib.Symbol17_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance_1 = new lib.bg2();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,320,480);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol24("synched",0);
	this.instance.setTransform(103.45,10.6,1.5,1.5,0,0,0,103.5,10.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.95,scaleY:0.95,x:103.5,alpha:1},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(831).to({startPosition:0},0).to({_off:true},1).wait(2196));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-87.5,-6.4,352.1,35.9);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol19("synched",0);
	this.instance.setTransform(98.8,36.55,1.5,1.5,0,0,0,98.8,9.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.95,scaleY:0.95,y:6.55,alpha:1},10,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:9.8},10,cjs.Ease.get(1)).wait(73).to({startPosition:0},0).to({_off:true},1).wait(4).to({_off:false},0).wait(244).to({startPosition:0},0).to({_off:true},1).wait(2007));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-86.7,-69.5,335.4,33.3);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol16("synched",0);
	this.instance.setTransform(334.65,86.25,0.4,0.4,0,0,0,334.7,86.3);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:334.6,scaleX:1.1,scaleY:1.1,x:334.6,y:86.35,alpha:1},8,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,y:86.3},7,cjs.Ease.get(1)).wait(267).to({startPosition:0},0).to({_off:true},1).wait(257));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85.1,-16.2,832.2,214.5);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol15("synched",0);
	this.instance.setTransform(103.8,-18,1,1,0,0,0,103.8,7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:9,alpha:1},8,cjs.Ease.get(1)).to({y:7},5,cjs.Ease.get(1)).wait(276).to({startPosition:0},0).to({_off:true},1).wait(150));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.3,-39,208,65.7);


(lib.Symbol11copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.setTransform(43.4,7.6,1,1,0,0,0,43.4,7.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.9,scaleY:0.9},9,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.4,-2.8,149.9,30.400000000000002);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12("synched",0);
	this.instance.setTransform(43.4,7.6,1,1,0,0,0,43.4,7.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14,cjs.Ease.get(1)).wait(12).to({startPosition:0},0).to({_off:true},1).wait(1938));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.4,-2.8,149.9,30.400000000000002);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_6
	this.instance = new lib.Symbol10("synched",0);
	this.instance.setTransform(71.4,186.45,1,1,0,0,0,120.6,10.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:156.4,alpha:1},8,cjs.Ease.quadOut).wait(262).to({startPosition:0},0).to({_off:true},1).wait(4023));

	// Layer_2
	this.instance_1 = new lib.Symbol4("synched",0);
	this.instance_1.setTransform(150.5,144.15,1,1,0,0,0,0,5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(6).to({_off:false},0).to({alpha:1},6,cjs.Ease.get(1)).wait(258).to({startPosition:0},0).to({_off:true},1).wait(4023));

	// Layer_4
	this.instance_2 = new lib.Symbol8("synched",0);
	this.instance_2.setTransform(211,116.9,1,1,0,0,0,66.5,13.3);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:128,alpha:1},8,cjs.Ease.quadOut).wait(262).to({startPosition:0},0).to({_off:true},1).wait(4023));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.4,103.2,338.79999999999995,80.49999999999999);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4
	this.instance = new lib.Symbol23("synched",0);
	this.instance.setTransform(82.5,-27.4,1,1,0,0,0,103.5,10.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(119).to({_off:false},0).wait(51).to({startPosition:51},0).to({_off:true},1).wait(800));

	// Layer_2
	this.instance_1 = new lib.Symbol22("synched",0);
	this.instance_1.setTransform(90.6,10.15,2,2,0,0,0,107.5,49.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(99).to({_off:false},0).to({regY:49,scaleX:1,scaleY:1,x:90.5,y:60,alpha:1},18,cjs.Ease.get(1)).wait(53).to({startPosition:0},0).to({_off:true},1).wait(800));

	// Layer_11
	this.instance_2 = new lib.Symbol18("synched",0);
	this.instance_2.setTransform(81.8,32.8,1,1,0,0,0,98.8,9.8);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).wait(80).to({startPosition:80},0).to({alpha:0,startPosition:98},14,cjs.Ease.get(1)).wait(57).to({startPosition:155},0).to({_off:true},1).wait(800));

	// Layer_1
	this.instance_3 = new lib.Symbol21("synched",0);
	this.instance_3.setTransform(83.05,86.5,2,2,0,0,0,83,86.5);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({scaleX:1,scaleY:1,x:83,alpha:1},17,cjs.Ease.get(1)).wait(82).to({startPosition:0},0).to({alpha:0},14,cjs.Ease.get(1)).wait(57).to({startPosition:0},0).to({_off:true},1).wait(188).to({_off:false},0).wait(612));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-264.3,-182,645.4000000000001,480);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_289 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(289).call(this.frame_289).wait(1));

	// cta copy
	this.instance = new lib.Symbol11copy();
	this.instance.setTransform(162.55,383.1,0.77,0.77,0,0,0,43.6,7.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(68).to({_off:false},0).wait(222));

	// cta
	this.instance_1 = new lib.Symbol11("synched",0);
	this.instance_1.setTransform(162.65,383.25,0.77,0.77,0,0,0,43.7,8.1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41).to({_off:false},0).to({_off:true},27).wait(222));

	// Layer_7
	this.instance_2 = new lib.Symbol20("synched",0);
	this.instance_2.setTransform(171,269.5,1,1,0,0,0,83,86.5);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(119).to({_off:false},0).wait(171));

	// logo
	this.instance_3 = new lib.Logo();
	this.instance_3.setTransform(121,421,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(290));

	// Layer_9
	this.instance_4 = new lib.Symbol14("synched",0);
	this.instance_4.setTransform(166.4,209.4,1,1,0,0,0,334.4,86.4);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(7).to({_off:false},0).wait(112).to({startPosition:112},0).to({x:167.4,y:118.4,startPosition:130},18,cjs.Ease.get(1)).wait(153));

	// Layer_8 copy
	this.instance_5 = new lib.Symbol17_1("synched",0);
	this.instance_5.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(119).to({_off:false},0).to({alpha:1},11,cjs.Ease.get(1)).wait(160));

	// Layer_6
	this.instance_6 = new lib.Symbol13("synched",0);
	this.instance_6.setTransform(165.55,122.5,0.89,0.89,0,0,0,104,7.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(290));

	// Layer_5
	this.instance_7 = new lib.Symbol5("synched",0);
	this.instance_7.setTransform(87.8,222.8,1,1,0,0,0,62.8,63.8);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(19).to({_off:false},0).wait(271));

	// Layer_8
	this.instance_8 = new lib.Symbol17("synched",0);
	this.instance_8.setTransform(160,240,1,1,0,0,0,160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(290));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-253,0,832.1,480);


// stage content:
(lib._320x480 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.main();
	this.instance.setTransform(150,150,1,1,0,0,0,150,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(160,240,160,240);
// library properties:
lib.properties = {
	id: 'CC7D37763753984998DC0DE70763E649',
	width: 320,
	height: 480,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg2.jpg?1694524480675", id:"bg2"},
		{src:"images/h2.png?1694524480675", id:"h2"},
		{src:"images/h3.png?1694524480675", id:"h3"},
		{src:"images/light.png?1694524480675", id:"light"},
		{src:"images/Logo.png?1694524480675", id:"Logo"},
		{src:"images/Rectangl.png?1694524480675", id:"Rectangl"},
		{src:"images/tagline.png?1694524480675", id:"tagline"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CC7D37763753984998DC0DE70763E649'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;